### DISCUSSION TITLE
How do I use Dependabot to keep this action up to date?

### DISCUSSION THREAD

**Discussion by JamesIves** [JamesIves/github-pages-deploy-action#1004] [Q&A] [answered]
The README mentions using Dependabot to keep the action up to date. How do I do this?

**Comment by JamesIves** [comment, marked as answer]
To have Dependabot create version bump pull requests within your project simply add a `.github/dependabot.yml` file with the following:

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
    open-pull-requests-limit: 10
```

Dependabot will create daily checks against your project and make pull requests for you increasing the version number whenever a newer iteration of the action is available. You can [learn more about Dependabot here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically).
