### DISCUSSION TITLE
Permissions error

### DISCUSSION THREAD

**Discussion by raquelalegre** [JamesIves/github-pages-deploy-action#1011] [Q&A] [answered]
I am getting a permissions error that I am confused about.
This is a public repository, and from the instructions it sounds like I don't need to set up any deploy keys or ssh keys. I understand it's just the GITHUB_TOKEN that is being used behind the scenes and gets created automatically by GH Actions. 

The error message says:

```
[...]
Switched to a new branch 'github-pages-deploy-action/grtnldvn6'
/usr/bin/git commit -m Deploying to gh-pages from @ UCL/UKCORDEX-plot-explorer-dev@2a76146fab2df470abb4af4bdc912d4badeefbfd 🚀 --quiet --no-verify
/usr/bin/git push --force ***github.com/UCL/UKCORDEX-plot-explorer-dev.git github-pages-deploy-action/grtnldvn6:gh-pages
remote: Permission to UCL/UKCORDEX-plot-explorer-dev.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/UCL/UKCORDEX-plot-explorer-dev.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/grtnldvn6
Reset branch 'github-pages-deploy-action/grtnldvn6'
/usr/bin/chmod -R 777 github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
[...]
```

The complete log is in https://github.com/UCL/UKCORDEX-plot-explorer-dev/runs/4868866705?check_suite_focus=true

This is my workflow:

```
name: Deploy React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # We will deploy with only one version of node  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}    
      - name: npm ci and build
        run: |
          npm ci
          npm run build --if-present
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
```

**Comment by JamesIves** [comment]
Morning,

Are you running this workflow within an organization? If so it might be necessary for you to provide a `token` parameter with a PAT from a service account that has push permissions to that repository. Sometimes the built-in token provided by the GitHub workflow runner doesn't have adequate permissions and this error will sometimes throw. [The README has some additional details on how you can set this up](https://github.com/JamesIves/github-pages-deploy-action#configuration-).

```yml
 - name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@v4.2.2
   with:
      branch: gh-pages
      folder: build
      token: ${{ secrets.PAT }}
```

**Comment by raquelalegre** [comment]
Thank you for your quick answer! This makes sense, as everything worked when I tried the website on my own user organisation, but it didn't once I tried it in the work one. 
I'm still confused about how to proceed. Do I need to create a PAT in the repository secrets, or at the organisation level? What's your GH action validating that token value against?

**Reply by raquelalegre** [reply]
Ok, so my last question didn't make sense because I didn't quite get how to configure a PAT 0:) 
All understood now! 

Also, something I want to try is to specify permissions for the GITHUB_TOKEN explicitly in the workflow. I'll test both ways (PAT and explicitly permissions in workflow) and report how it went in case it helps someone else in the future.

**Comment by raquelalegre** [comment]
With the PAT token I got a different error:

https://github.com/UCL/UKCORDEX-plot-explorer-dev/runs/4881033071?check_suite_focus=true#step:5:49

```
[...]
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/UCL/UKCORDEX-plot-explorer-dev.git/'
[...]
```

**Reply by raquelalegre** [reply]
And the explicit setup of write permissions for the job also didn't work. I've also tried giving more permissions to the PAT token, but still get the same error about username/password. I'm blocked :(

**Reply by raquelalegre** [reply]
Using `ssh-key` also gave me the older error message:

```
remote: Permission to UCL/UKCORDEX-plot-explorer-dev.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/UCL/UKCORDEX-plot-explorer-dev.git/': The requested URL returned error: 403
```

**Reply by JamesIves** [reply]
The personal access token that you generate needs to have adequate read/write permissions over that specific repository. The correct process for this would be to:

* Create a new user, or assign an existing user read/write permissions over the repository you want to deploy to within that organization, so they personally can push to it. 
* Generate a personal access token from that users account that provides organization permission levels. The reason I mentioned create a new user is so you're not providing the bot more permissions than it needs, but in some cases this may not be necessary/possible. 
* Assign the `token` parameter in the `github-pages-deploy-action` step via a repository level secret.

If you're getting invalid username/password it means that your PAT isn't scoped correctly and it's hitting a permission error, or it's not being assigned correctly. You can think of this as extending personal permissions to the github-actions bot so it can make commits on your behalf. The steps are similar but not quite the exact same for the ssh-key parameter, you can learn how to do that [here](https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-).

Can you also provide your workflow examples for the failed runs above? Additionally can you verify that you added the generated PAT to the `Settings > Secrets` menu within the org you're configuring the workflow on?

**Reply by JamesIves** [reply]
Taking another look at your workflow at the top of this thread it looks like there's no `token` parameter set. You need to have something like this configured with `${{ secrets.PAT }}` pointing to the secret you named in your repository secrets menu:

```yml
 - name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@v4.2.2
   with:
      branch: gh-pages
      folder: build
      token: ${{ secrets.PAT }}
```

The logging here isn't very good (and will be improved in 4.3.0) but you can see the action logs `Deploying using …… 🔑` which indicates it doesn't have a valid key setup. It would normally say `SSH Key` or `Deploy Key` depending on what is configured.
