### DISCUSSION TITLE
[Deploy merge instead delete old files] can i deploy use merge instead removing all old files ?

### DISCUSSION THREAD

**Discussion by dimaslanjaka** [JamesIves/github-pages-deploy-action#1070] [Q&A]
i have a lot nodejs process, and they have separated runner.
i want deploy to my github pages with `pull` first instead `push --force` directly. so, my other old files not be deleted after deployed
- ive searched [google](https://www.google.com/search?q=JamesIves%2Fgithub-pages-deploy-action+pull&client=firefox-b-d&sxsrf=APq-WBvtslQ5l2QCFNfM85c0fSHALihG1Q%3A1649119005877&ei=HY9LYpmbNd3B3LUP556WwAE&ved=0ahUKEwjZnaaE1_v2AhXdILcAHWePBRgQ4dUDCA0&uact=5&oq=JamesIves%2Fgithub-pages-deploy-action+pull&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECc6BwgAEEcQsAM6BAgAEB5KBAhBGABKBAhGGABQmQVY5QtggQ5oAXABeACAAZcBiAH2BJIBAzEuNJgBAKABAcgBCcABAQ&sclient=gws-wiz), no solution

my sample 1 workflow
```yaml
name: Build

on:
  push:
    branches:
      - compiler # run when this branch pushed

# cancel previous workflows, run only one workflow
concurrency:
  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    #if: {{ $false }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192 4096 --expose-gc
      GITFLOW: true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Setup GitHub
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get Caches
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
            ~/.npm
            ./tmp
            ./build
            ./packages
            ./databases
          key: ${{ runner.os }}-xnodex-${{ hashFiles('**/.guid') }}
          restore-keys: ${{ runner.os }}-xnodex-
      - run: npm i -g npm hexo-cli gulp-cli typescript ts-node
        # run global install when cache not written
        # if: steps.npm-cache.outputs.cache-hit != 'true'
      #- run: rm -rf node_modules tmp build
        # run if commit contains substring 'clean cache'
        #if: "contains(github.event.head_commit.message, 'clean cache')"
      - run: npm install
      - run: "gulp copy:assets"
      - run: "gulp copy:posts"
      - run: "gulp generate:assets"
      - run: "gulp generate:template"
      - run: "gulp generate:posts"
      - run: "gulp generate:after"
      - run: cp -rf docs/sitemap.html docs/index.html
      - run: cd docs/page && npm install
      - run: cp -rf source/robots.txt docs/robots.txt
      - run: echo www.webmanajemen.com > docs/CNAME
      - name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
```

**Comment by JamesIves** [comment]
Might be worth checking out the `force` option that was released in yesterday's update, I think toggling it to `false` might be helpful.

**Reply by dimaslanjaka** [reply]
> Might be worth checking out the `force` option that was released in yesterday's update, I think toggling it to `false` might be helpful.

like this ?
```yaml
- name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          force: false # merge instead push --force, (keep old / non modified) files?
```

**Reply by JamesIves** [reply]
You'd also need to update to the latest version, but yeah.

**Reply by dimaslanjaka** [reply]
> You'd also need to update to the latest version, but yeah.

not working. old files still deleted. this action cannot run on separated workflow yml files. old files (not modified) on existing repo got deleted.
```yaml
- name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          force: false # merge instead push --force, (keep old / non modified) files?
```
also this not working
```yaml
- name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          force: false # merge instead push --force, (keep old / non modified) files?
```

**Reply by dimaslanjaka** [reply]
i need action that runs:
```bash
git pull # fetch old files from repository
# process files here
git add -A # add modified files
git push origin ${branch-name} # push
```
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
```bash
.github/workflows/page1.yml 
.github/workflows/page2.yml # the files from page1.yml not restored
```

**Comment by dimaslanjaka** [comment]
actually this is for cache strategy, so process won't be repeated for files that are not changed (like articles for example). so the process only runs for files that have been managed or new files (new article). and the old files are left alone because they don't need to be forced (save time)

**Reply by dimaslanjaka** [reply]
i using this to manage my github page within more than 1000 posts, so i dont need to repeat all file processes

**Reply by dimaslanjaka** [reply]
nodejs can't process 1000+ files at once. so it must be separated. Therefore, a 'git action deployer' which can be merged with the previous file is needed

**Reply by dimaslanjaka** [reply]
my full config
```yaml
name: Build

on:
  push:
    branches:
      - compiler # run when this branch pushed

# cancel previous workflows, run only one workflow
concurrency:
  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  #cancel-in-progress: true

jobs:
  build:
    if: {{ $false }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192 4096 --expose-gc
      GITFLOW: true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Setup GitHub
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get Caches
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
            ~/.npm
            ./tmp
            ./build
            ./packages
            ./databases
          key: ${{ runner.os }}-xnodex-${{ hashFiles('**/.guid') }}
          restore-keys: ${{ runner.os }}-xnodex-
      - run: npm i -g npm hexo-cli gulp-cli typescript ts-node
        # run global install when cache not written
        # if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm install
      - run: gulp clean
        if: "contains(github.event.head_commit.message, 'clean cache')"
      - run: "gulp copy:assets"
      - run: "gulp copy:posts"
      - run: "gulp generate:assets"
      - run: "gulp generate:template"
      - run: "gulp generate:posts"
      - run: "gulp generate:after"
      #- run: cp -rf docs/sitemap.html docs/index.html
      - run: cd docs/page && npm install
      - run: cp -rf source/robots.txt docs/robots.txt
      #- run: cp -rf .gitignore docs/.gitignore
      - run: cp -rf README.md docs/readme.md
      - run: echo www.webmanajemen.com > docs/CNAME
      - name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          force: false # merge instead push --force, (keep old / non modified) files?
```

**Reply by dimaslanjaka** [reply]
so, now i just manually copy the public files to github page branch

**Comment by dimaslanjaka** [comment]
look. index.html got removed, iam not modifying index.html at all. leaving only `readme.md` alone

![image](https://user-images.githubusercontent.com/12471057/162436595-0f083f00-190f-46d1-b1b0-fd09328a89e4.png)

**Comment by dimaslanjaka** [comment]
This work, but only for local process. not working when i run this on 'github action'.

https://github.com/dimaslanjaka/dimaslanjaka.github.io/blob/compiler/src/gulp/tasks/deploy.ts

**Reply by dimaslanjaka** [reply]
I can't write articles directly from github when I'm not in front of the computer, because not deployed by `github action`

**Comment by dimaslanjaka** [comment]
I've confirmed, JamesIves/github-pages-deploy-action@4.1.4 still deletes old files and pushes them right away

**Comment by dimaslanjaka** [comment]
SOLUTION: cache the public directory to keep old processed files
```yaml
- name: Get Caches
    id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
    uses: actions/cache@v2
    with:
      path: |
        ${{ steps.npm-cache-dir.outputs.dir }}
        ${{ steps.yarn-cache-dir-path.outputs.dir }}
        ./node_modules
        ~/.npm
        ./tmp
        ./build
        ./packages
        ./databases
        ./docs
      key: ${{ runner.os }}-xnodex-${{ hashFiles('**/.guid') }}
      restore-keys: ${{ runner.os }}-xnodex-
- name: Deploy 🚀
    #if: ${{ false }}
    #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
    uses: JamesIves/github-pages-deploy-action@v4.3.0
    with:
      branch: master # The branch the action should deploy to.
      folder: docs # The folder the action should deploy.
      force: false # merge instead push --force, (keep old / non modified) files?
```
