### DISCUSSION TITLE
how to include files that are in .gitignore?

### DISCUSSION THREAD

**Discussion by maxandersen** [JamesIves/github-pages-deploy-action#1116] [Q&A]
I got a site where html files are generated but since I don't want them committed into main branch I have `*.html` in my .gitignore
which results in that the deploy to github does not include the html files.

Is there a way to tell github-pages-deploy-action to explicitly  include certain file names/patterns in its commit or tell it to ignore .gitignore ?

**Comment by Skyost** [comment]
I'm currently facing the same problem. Have you found a solution @maxandersen ?

**Reply by maxandersen** [reply]
Unfortunately not.

**Comment by JamesIves** [comment]
What does your workflow look like? 
Technically you could just delete the git ignore file after you've run your build script prior to deployment.

**Reply by maxandersen** [reply]
If I delete the gitignore then other files that shouldn't be posted gets added. 

I guess I could remove the *.html line from .gitignore before it pushes ?

**Reply by JamesIves** [reply]
_Please_ include your workflow. Otherwise, I'm just guessing how your workflow is deploying.

**Reply by maxandersen** [reply]
Sorry - my brain missed you were asking about the yml workflow and not just in general. 

Here is one https://github.com/maxandersen/breaking-eggs-with-quarkus/blob/main/.github/workflows/ghpages.yml

This project currently don't have a html in gitignore but I wish I could.

**Comment by renatocassino** [comment]
I want to add a new folder but generated in pipeline. How can I do to upload?

I have in my structure a folder called _posts with markdowns and I have a subfolder with a project. I want to send this subfolder to another branch but add the _posts to there

I made this:

```yaml
      - name: Copy posts to server folder
        run: cp -r ./_posts ./my-server

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: server # The branch the action should deploy to.
          FOLDER: my-server # The folder the action should deploy.
```

But this doesnt work :/

How can I do to upload _posts copied?
