### DISCUSSION TITLE
Error message seems to be informational, non-error condition

### DISCUSSION THREAD

**Discussion by PartyLich** [JamesIves/github-pages-deploy-action#1162] [Q&A]
I had attempted to use this action as part of a workflow that would ultimately open a PR to `gh-pages`, but encountered some behavior I did not expect. I'm getting an error as follows:
```
...
Pushing changes… (attempt 1 of 3)
/usr/bin/git push --porcelain ***github.com/PartyLich/cleopatra_cairo.git github-pages-deploy-action/mse3qzb3g:gh-pages_3df3d13
remote: 
remote: Create a pull request for 'gh-pages_3df3d13' on GitHub by visiting:        
remote:      https://github.com/PartyLich/cleopatra_cairo/pull/new/gh-pages_3df3d13
remote: 
To https://github.com/PartyLich/cleopatra_cairo.git
*	refs/heads/github-pages-deploy-action/mse3qzb3g:refs/heads/gh-pages_3df3d13	[new branch]
Done
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/mse3qzb3g
Reset branch 'github-pages-deploy-action/mse3qzb3g'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: remote: 
remote: Create a pull request for 'gh-pages_3df3d13' on GitHub by visiting:        
remote:      https://github.com/PartyLich/cleopatra_cairo/pull/new/gh-pages_3df3d13
remote: ❌
Notice: Deployment failed! ❌

```
The error message displayed isn't a failure at all, it's an informational message about creating a PR from the new branch. But it's printing to stderr, and the [current implementation](https://github.com/JamesIves/github-pages-deploy-action/blob/e8f5095e8b3af3fe1ccbf3c02eb56828c3f0975d/src/git.ts#L311-L313) treats this as an error and fails the workflow.

This seems like a bug (misidentification of failure condition), but perhaps it's something I've done.

The workflow at the time was
```yaml
name: docs
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Make Docs
      run: make docs
    - name: Jekyll fix
      run: touch target/doc/.nojekyll
    - name: Set short sha output
      id: short_sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
    - name: Update gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages_${{ steps.short_sha.outputs.sha }}
        clean: false
        commit-message: update html docs for ${{ github.sha }}
        folder: target/doc
        force: false
```
I've since fixed this and extended the functionality i needed (separate base and target branches, pr opening) in a fork, but if it is considered a bug for the upstream action I'll open an issue. If it's not a bug, I'd love to know what I did wrong or how my expectations were misguided.
