### DISCUSSION TITLE
How to deploy to a different repo?

### DISCUSSION THREAD

**Discussion by 0xSwego** [JamesIves/github-pages-deploy-action#1163] [Q&A]
My current configuration is this:

```
name: Deploy to Github Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          repository-name: other-repo
```

But I get this error:
![image](https://user-images.githubusercontent.com/21270278/178150851-773c041a-c091-4a50-ae1d-9f839c1f7ba1.png)

I read about the access token here: https://github.com/JamesIves/github-pages-deploy-action/discussions/537
but I cannot figure out how to set it up.

Is there a guide I can follow or someone so kind to tell me? 🤓
