### DISCUSSION TITLE
How to configure for side-by-side checkouts and an environment variable?

### DISCUSSION THREAD

**Discussion by fuhrmanator** [JamesIves/github-pages-deploy-action#1174] [Q&A]
Hello,

I'm using a [side-by-side check-out](https://github.com/actions/checkout#checkout-multiple-repos-side-by-side) (where the second repo is a tool I run in my CI). 

I want to deploy a folder that's in only one of the repos, e.g. `main/$SOURCE_ROOT`, but I can't get it to work.

I set the `folder:`  to be just `.` as a basic trial, and I get an error that seems to imply the action is totally confused about the path. 

Here's a real example: https://github.com/fuhrmanator/Head-First-Design-Patterns/runs/7502602445?check_suite_focus=true

```
/usr/bin/git config --global --add safe.directory /home/runner/work/Head-First-Design-Patterns/Head-First-Design-Patterns
```
~~`Head-First-Design-Patterns` is being repeated. The true path is `main/Head-First-Design-Patterns` (because of how I installed it with checkout's side-by-side).~~

~~Passing in environment variables to `folder:` , e.g., `$GITHUB_WORKSPACE/main/$SOURCE_ROOT` doesn't seem to work. They aren't substituted (the error says something like `$GITHUB_WORKSPACE/main/$SOURCE_ROOT does not exist`.~~

My apologies if this is something obvious - I'm new to Actions.

----

ETA:

Getting closer. According to [the doc](https://github.com/marketplace/actions/deploy-to-github-pages#required-setup) adding a `~` to the end will make it an absolute path. So, I tried:

```yaml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.repository }}/main/${{ env.SOURCE_ROOT}}/~
```

The error is still in the folder path:

> Error: The directory you're trying to deploy named `/home/runner/work/Head-First-Design-Patterns/Head-First-Design-Patterns/main/src/~` doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗

If I remove the `~`, the action is confused because it doesn't think it's a git repo:

```yaml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/main/$${{ env.SOURCE_ROOT }}
```

> Checking configuration and starting deployment… 🚦  
Deploying using Deploy Token… 🔑  
Configuring git…  
/usr/bin/git config --global --add safe.directory /home/runner/work/Head-First-Design-Patterns/Head-First-Design-Patterns  
/usr/bin/git config user.name fuhrmanator  
fatal: not in a git directory  
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌  
Notice: Deployment failed! ❌

It seems the action doesn't like the idea of side-by-side repos.
