### DISCUSSION TITLE
Experiencing "Invalid username or password" git error in workflow which deploys to a separate repository

### DISCUSSION THREAD

**Discussion by jjliggett** [JamesIves/github-pages-deploy-action#1264] [Q&A] [answered]
Original title: Multiple different git errors in workflow which deploys to two repositories

I'm encountering ~~multiple different~~ git errors with the following GitHub workflow which deploys to a dev environment during pull requests and then to the main repository when merged: https://github.com/jjliggett/CurrentTimeApp/blob/root/.github/workflows/actions.yaml

UPDATE: Previously, I was experiencing issues with the Production deployment in addition to issues with deployments to the separate dev environment, but now - after updating the action, the Production deployment is working. The dev environment deployment is still failing.

The workflow had worked before, but all of the sudden, both deployments started failing.

The production deployment most recently passed on September 18th and has started failing since then (until merging the new action update), with the error first occurring from an update to actions/checkout (from version 3.0.2 to version 3.1.0) as shown in the commit history here:

![image](https://user-images.githubusercontent.com/67353173/199637986-a0e4d379-dfc4-4925-8404-7570955b58e6.png)

![image](https://user-images.githubusercontent.com/67353173/199638108-b66e3771-064a-4c5c-ba43-d4c4707ac478.png)

https://github.com/jjliggett/CurrentTimeApp/commits/root

UPDATE: Prior to the update of the action in https://github.com/jjliggett/CurrentTimeApp/pull/67#issuecomment-1312842251 , it was failing with the following error:

```
remote: Permission to jjliggett/CurrentTimeApp.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jjliggett/CurrentTimeApp.git/': The requested URL returned error: 403
```

( https://github.com/jjliggett/CurrentTimeApp/actions/runs/3262192429/jobs/5617156506 )

From other discussions, I checked the Actions permissions for the CurrentTimeApp repository and the Workflow permissions are set to "Read and write permissions".

In addition to that error, I am also encountering an issue with a dev environment deployment, as seen with this dependabot pull request that updates the JamesIves/github-pages-deploy-action to the new version 4.4.1: https://github.com/jjliggett/CurrentTimeApp/pull/67

This failure also happened all of the sudden, without a change to the personal access token.

As noted in that pull request, I tested with a new fine-grained token with Read and Write access to code, commit statuses, and pages, for the dev-env repository and this did not solve the issue. I then tested again later with another fine-grained token with Read and Write access to actions, code, commit statuses, environments, pages, pull requests, and workflows for the dev-env repository. This also did not solve the problem.

This error is slightly different from the Production deployment error, specifically the following:

```
/usr/bin/git checkout -b github-pages-deploy-action/t904nqrea
Switched to a new branch 'github-pages-deploy-action/t904nqrea'
/usr/bin/git commit -m Deploying to gh-pages from @ jjliggett/CurrentTimeApp@29b3ce632dc574b5f5140a273f2af24c881ef3bf 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/jjliggett/CurrentTimeApp-dev-env.git github-pages-deploy-action/t904nqrea:gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/jjliggett/CurrentTimeApp-dev-env.git/'
Running post deployment cleanup jobs… 🗑️
```

A more recent instance of this error can be found from this PR workflow: https://github.com/jjliggett/CurrentTimeApp/pull/69 with the following workflow log: https://github.com/jjliggett/CurrentTimeApp/actions/runs/3457305907/jobs/5770658467

Does anyone have any other ideas for me to explore to address this error?

**Comment by jjliggett** [comment, marked as answer]
From more troubleshooting, I have identified the issue. It was a syntax error within the GitHub workflow.

Previously:

```yaml
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          repository-name: jjliggett/CurrentTimeApp-dev-env
          token: "${{ secrets.DEV_PAT_TOKEN }}"
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
          single-commit: true
```

I made the following pull request which removes the quotes around the token secret and the workflow is now succeeding:

https://github.com/jjliggett/CurrentTimeApp/pull/75/files#diff-8f2eca09d947cd98b9bbfacccdf370888a3bac49b0519afbc37dd69e4f89defbR85

After:

```yaml
      - name: Publish application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          repository-name: jjliggett/CurrentTimeApp-dev-env
          token: ${{ secrets.DEV_PAT_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
          git-config-name: jjliggett
          git-config-email: 67353173+jjliggett@users.noreply.github.com
          single-commit: true
```

https://github.com/jjliggett/CurrentTimeApp/blob/faa16100c9f0f1d720a138ee743b3e2382abff29/.github/workflows/actions.yaml#L85

This workflow was working with quotes around the token secret before. I'm not sure exactly why this broke, but it looks like we cannot use quotes around the tokens in the workflow now.
