### DISCUSSION TITLE
How to add signed commits with Github action?

### DISCUSSION THREAD

**Discussion by japananh** [JamesIves/github-pages-deploy-action#1350] [Q&A]
I want to add **signed commits** to my repo.

<img width="1277" alt="Screenshot 2023-04-05 at 14 52 46" src="https://user-images.githubusercontent.com/29560157/230017102-2c9e54f8-88ba-4439-95b7-b1dfd8cb54dd.png">

I tried to import a GPG key with [`crazy-max/ghaction-import-gpg@v5`](crazy-max/ghaction-import-gpg@v5) action but it caused an error.

> "Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌".

If I remove this `crazy-max/ghaction-import-gpg@v5` workflow, there will be no error with `Jameslves/github-pages-deploy-action`.

I read some issues such as [308](https://github.com/JamesIves/github-pages-deploy-action/issues/308) but it didn't help much.

What's wrong with my workflow? How do I add signed commits to my repo?

<img width="835" alt="Screenshot 2023-04-05 at 14 26 57" src="https://user-images.githubusercontent.com/29560157/230011552-029b407d-c429-4267-9dd8-0839c8b5190a.png">

My workflow

```yml

name: Deploy to Github Pages

on:
    push:
        branches: [main]

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{ secrets.API_TOKEN_GITHUB }}

            - name: Cache Hugo resources
              uses: actions/cache@v3
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v4
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Cache Go Modules
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            # Remove this workflow will fix error -------------------
            
            - name: Import GPG key
              id: import_gpg
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                git_user_signingkey: true
                git_commit_gpgsign: true

            # --------------------------------------------------------

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
                  silent: true
                  token: ${{ secrets.API_TOKEN_GITHUB }}

            - name: Push directory to another repository
              uses: cpina/github-action-push-to-another-repository@v1.5.1
              env:
                SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                source-directory: public
                destination-github-username: my-des-github-username
                destination-repository-name: my-repo
                user-email: my-email
                user-name: my-username
                target-branch: main
                commit-message: 'feat: add/update from the private repo'
```
