### DISCUSSION TITLE
Publishing to a directory /public

### DISCUSSION THREAD

**Discussion by frunkers** [JamesIves/github-pages-deploy-action#1518] [Q&A] [answered]
Due to the transition GitHub Actions of node version 16 to version 20, it was necessary to change version actions/checkout from 3 to 4. And the code in the branch **gh-pages** began to be published in the **/public** directory, and not to the **root** of the site. Because of this, the file is actions/checkout is not found and instead of the site I get a 404 error.

``` yml
name: Build Webpack
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.1

      - name: Install 📥
        run: npm ci

      - name: Build 📦
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
```

Before changes version
![image](https://github.com/JamesIves/github-pages-deploy-action/assets/63113266/ae5cb723-0b3a-497d-85f6-aeccf71ad7e8)

After changes version
![image](https://github.com/JamesIves/github-pages-deploy-action/assets/63113266/3b1cb45d-59a3-4e9e-a1a6-008ec71288a9)

I want to place the files at the root of the branch and I believe that your action packs them
