### DISCUSSION TITLE
请帮助我: Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌

### DISCUSSION THREAD

**Discussion by Pupper0601** [JamesIves/github-pages-deploy-action#1536] [Q&A]
``` bash
Run JamesIves/github-pages-deploy-action@v4

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/HexoNote/HexoNote
/usr/bin/git config user.name Pupper0601
/usr/bin/git config user.email 58965954+Pupper0601@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/Pupper0601/Pupper0601.github.io.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/Pupper0601/Pupper0601.github.io.git refs/heads/main
178ef8f7b02f7f42f72ce160b99420ae53040fc3	refs/heads/main
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin main
From https://github.com/Pupper0601/Pupper0601.github.io
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD d400abe)
/usr/bin/git checkout -B main origin/main
Previous HEAD position was d400abe 修复报错问题
Switched to and reset branch 'main'
branch 'main' set up to track 'origin/main'.
/usr/bin/chmod -R +rw /home/runner/work/HexoNote/HexoNote/public
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/HexoNote/HexoNote/public/. github-pages-deploy-action-temp-deployment-folder --delete --exclude public/.github --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/ampk7xbma
Switched to a new branch 'github-pages-deploy-action/ampk7xbma'
/usr/bin/git commit -m 修复报错问题 由Github Actions更新 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/Pupper0601/Pupper0601.github.io.git github-pages-deploy-action/ampk7xbma:main
remote: error: GH0[13](https://github.com/Pupper0601/HexoNote/actions/runs/8185321021/job/22381445895#step:9:14): Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at http://github.com/Pupper0601/Pupper0601.github.io/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - GITHUB PUSH PROTECTION        
remote:   ——————————————————————————————————————————————————————        
remote:    Resolve the following secrets before pushing again.        
remote:           
remote:    (?) Learn how to resolve a blocked push        
remote:    https://docs.github.com/code-security/secret-scanning/pushing-a-branch-blocked-by-push-protection        
remote:           
remote:    (?) This repository does not have Secret Scanning enabled, but is eligible. Enable Secret Scanning to view and manage detected secrets.        
remote:    Visit the repository settings page, https://github.com/Pupper0601/Pupper0601.github.io/settings/security_analysis        
remote:           
remote:           
remote:           
remote:   —— GitHub Personal Access Token ——————————————————————        
remote:    locations:        
remote:      - commit: a5f397[18](https://github.com/Pupper0601/HexoNote/actions/runs/8185321021/job/22381445895#step:9:19)e80dd9325de4300c10dcac845[24](https://github.com/Pupper0601/HexoNote/actions/runs/8185321021/job/22381445895#step:9:25)2d69c        
remote:        path: posts/e6c82bb0.html:1        
remote:           
remote:    (?) To push, remove secret from commit(s) or follow this URL to allow the secret.        
remote:    https://github.com/Pupper0601/Pupper0601.github.io/security/secret-scanning/unblock-secret/2dLoLN4oKZzOSiv9sxJX62sKfSh        
remote: 
To https://github.com/Pupper0[60](https://github.com/Pupper0601/HexoNote/actions/runs/8185321021/job/22381445895#step:9:61)1/Pupper0601.github.io.git
 ! [remote rejected] github-pages-deploy-action/ampk7xbma -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/Pupper0601/Pupper0601.github.io.git'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/ampk7xbma
Reset branch 'github-pages-deploy-action/ampk7xbma'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
Notice: Deployment failed! ❌
```
```yml
name: 自动部署
# 当有改动推送到master分支时，启动Action
# 教程文档 https://zhsher.cn/posts/8779/#4-3-%E6%96%B9%E6%A1%88%E4%B8%89
on:
  push:
    branches:
      - main
      # 2020年10月后github新建仓库默认分支改为main，注意更改

jobs: # 工作流
  deploy: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境
    name: 编译 hexo 博客

    steps:
      - name: 1. 拉取源代码
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 2. 拉取主题代码
        uses: actions/checkout@v4
        with:
          lfs: true
          repository: Pupper0601/hexo-theme-anzhiyu
          ref: my-theme
          path: themes/anzhiyu

      - name: 3. 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: 4. 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: 5. 缓存 Hexo
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('package-lock.json')}}

      - name: 6. 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install gulp-cli -g #全局安装gulp
          npm install --save

      - name: 7. 生成静态文件
        run: |
          hexo clean
          hexo bangumi -u #bilibili番剧更新
          hexo generate
          hexo algolia
          gulp
      - name: 8. 部署到Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ***
          repository-name: Pupper0601/Pupper0601.github.io
          branch: main
          folder: public
          clean-exclude: |
            public/.github
          commit-message: "${{ github.event.head_commit.message }} 由Github Actions更新"
```

请问这个问题如何解决
