### DISCUSSION TITLE
After 6106 runs, process suddenly started failing due to worktree in use

### DISCUSSION THREAD

**Discussion by xander2005** [JamesIves/github-pages-deploy-action#1589] [Q&A] [answered]
I've had an action running to deploy data from the YouTube API into my repository since last year with no issues, and it uses a very lightly modified version of the script shown in the full example from [fetch-api-data-action](https://github.com/JamesIves/fetch-api-data-action)
Before tweaks:
```
name: Refresh Feed
on:
  schedule:
    - cron: 10 15 * * 0-6
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://example.com
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'

      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.
```
After tweaks:
```
name: Refresh Feed
on: workflow_dispatch
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=10&playlistId=UU_zkRpcTX_4aHjEeYK_tg7A&key=${{ secrets.API_KEY }}
          configuration: '{ "method": "GET" }'

      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: fetch-api-data-action
          target-folder: data
          clean: false
```
This has been working flawlessly, with the permissions in my settings allowing read and write access for actions. But 4 hours ago, I got an email saying that it failed. Here are relevant logs:
```
Run JamesIves/github-pages-deploy-action@v4

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es/

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/API-Fetch-Testing/API-Fetch-Testing
/usr/bin/git config user.name xander2005
/usr/bin/git config user.email xander2005@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
Unable to unset previous git config authentication as it may not exist, continuing…
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/xander2005/API-Fetch-Testing.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/xander2005/API-Fetch-Testing.git refs/heads/main
4ec1bcd35ddb021f1683674113d7ba77ad6f5c00	refs/heads/main
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin main
From https://github.com/xander2005/API-Fetch-Testing
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 4ec1bcd)
/usr/bin/git checkout -B main origin/main
fatal: 'main' is already used by worktree at '/home/runner/work/API-Fetch-Testing/API-Fetch-Testing'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/teh2b4ids
Switched to a new branch 'github-pages-deploy-action/teh2b4ids'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: There was an error creating the worktree: The process '/usr/bin/git' failed with exit code 128 ❌ ❌
Notice: Deployment failed! ❌
```
Note that I have looked at other issues in this repository where people have experienced exit code 128, tried all solutions mentioned in those issues, and it made no difference. The mentioned solutions were running with the GITHUB_TOKEN secret, and adding write permissions for content within the workflow file. Made no difference whether I had it or not, I'm curious as to why it spontaneously stopped working. My last commit before today was probably within the same month that I configured the action.

**Comment by JJLibra** [comment]
I also encountered a similar problem.
```
Run JamesIves/github-pages-deploy-action@v4
  

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/blog-source/blog-source
/usr/bin/git config user.name JJLibra
/usr/bin/git config user.email [11](https://github.com/JJLibra/blog-source/actions/runs/9124492338/job/25088773982#step:8:12)1830843+JJLibra@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/JJLibra/JJLibra.github.io.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/JJLibra/JJLibra.github.io.git refs/heads/main
df4462c8ee365ab903fcc46f39fa5fbd6d200f8f	refs/heads/main
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin main
From https://github.com/JJLibra/JJLibra.github.io
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 6f2cc8e)
/usr/bin/git checkout -B main origin/main
fatal: 'main' is already used by worktree at '/home/runner/work/blog-source/blog-source'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/0xnxwx8xl
Switched to a new branch 'github-pages-deploy-action/0xnxwx8xl'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: There was an error creating the worktree: The process '/usr/bin/git' failed with exit code [12](https://github.com/JJLibra/blog-source/actions/runs/9124492338/job/25088773982#step:8:13)8 ❌ ❌
Notice: Deployment failed! ❌
```

**Reply by JJLibra** [reply]
It was still running normally two days ago.

**Comment by JamesIves** [comment]
Is this consistently failing, or have you tried running it since? The worktree still in use error makes me wonder if you need to add the concurrency property mentioned in the README.

**Reply by xander2005** [reply]
It is consistently failing, even on the fresh repository, but I wonder if concurrency would still help. I'll mess around with it a little bit, and see if I can get something to work.

**Comment by LukeHollandDev** [comment]
@xander2005 @JJLibra @JamesIves 
I was having this same issue, I changed branch to try out some changes to my pipeline. Then it started working again.
The worktree error I believe is the key issue. @JJLibra @xander2005 try using a different branch just to see if it works.

I was getting this error: `fatal: 'main' is already used by worktree at '/home/runner/work/portfolio/portfolio'`
Then on my new branch the pipeline run just fine.

I feel like the error might be something to do with the main branch, I was running the action on the main branch while deploying to the main branch of my other repository. I think that because the pipeline was running on my main branch and then the action is doing a checkout with -B flag to main in the target branch was causing some sort of conflict.

The error for me occurred right after `/usr/bin/git checkout -B main origin/main`

Common denominator appears to be using the branch name as "main".

**Reply by JamesIves** [reply]
Interesting- I wonder if something has changed. I'm noticing that my sponsor jobs are failing today also with the same error. Haven't actually updated anything in either action 🤔

These jobs use the branch dev, but in all cases that is the base branch. Wondering if there's a way to more gracefully handle this error, where we instead use the existing worktree if this step complains of one already existing.

**Reply by xander2005** [reply]
@JamesIves @LukeHollandDev I have tried adding concurrency, but it didn't seem to change anything. Then, I ran the jobs on a different branch and it finished successfully. It's likely I'll have to stop the workflow from running on the main branch and set up a branch specially for running the jobs and push it to the main branch as a temporary fix.

**Comment by jaydrogers** [comment]
Just adding more data if this helps debug the issue. I am using the following workflow for [serversideup/docker-php](https://github.com/serversideup/docker-php/).

I also had this workflow working for about a year until today. Glad I was able to discover this thread.

Here is my set up if this helps in any way:

### Workflow:

```yml
name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          organization: true
          minimum: 501
          maximum: 5000
          token: ${{ secrets.SPONSORS_README_ACTION_PERSONAL_ACCESS_TOKEN }}
          marker: 'bronze'
          template: '* [{{{ name }}}]({{{ url }}}) - {{{ login }}}'
          file: 'README.md'

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          organization: true
          maximum: 500
          fallback: '<p align="center"><a href="https://github.com/sponsors/serversideup"><img src="https://521public.s3.amazonaws.com/serversideup/sponsors/sponsor-empty-state.png" alt="Sponsors"></a></p>'
          token: ${{ secrets.SPONSORS_README_ACTION_PERSONAL_ACCESS_TOKEN }}
          marker: 'supporters'
          template: '<a href="https://github.com/{{{ login }}}"><img src="https://github.com/{{{ login }}}.png" width="40px" alt="{{{ login }}}" /></a>&nbsp;&nbsp;'
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
```

### Error
Full log: https://github.com/serversideup/docker-php/actions/runs/9131257941/job/25110053326

![Screenshot 2024-05-17 at 11 28 46@2x](https://github.com/JamesIves/github-pages-deploy-action/assets/3174134/cc0568f5-a54f-4b55-ae6a-08840a2f44e2)

Thanks for your work @JamesIves! Much respect to you for maintaining this project 🤜💥🤛
