### DISCUSSION TITLE
GitHub Actions Build Successful, But Website Doesn't Reflect Code Changes

### DISCUSSION THREAD

**Discussion by BillyBrown237** [JamesIves/github-pages-deploy-action#1594] [Q&A]
I'm working on a project hosted on GitHub and using a build pipeline with GitHub Actions. While the build pipeline executes successfully, the changes I make to my project files aren't reflected on my live website. Here's a breakdown of what I'm experiencing:

Build Pipeline: My build pipeline seems to be working correctly. It fetches code from the repository, builds it (if necessary), and presumably completes all defined steps.
Code Changes: I've confirmed that the changes I make to my files are committed and pushed to the GitHub repository successfully.
Website Not Updated: However, when I visit my live website, the changes to  are not reflected. It displays a crashed verison of the file 

```yaml
name: Deploy Next.js site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=pnpm" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi


      - name: Install pnpm
        if: steps.detect-package-manager.outputs.manager == 'pnpm'
        run: |
          npm install -g pnpm
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml', '**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml', '**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.runner }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.next

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        ```
        
![Screenshot 2024-05-19 034751](https://github.com/JamesIves/github-pages-deploy-action/assets/80011561/701eb324-6f53-4013-b7d8-c1bc3bc80a5b)
