### DISCUSSION TITLE
"fatal: not in a git directory" "The process '/usr/bin/git' failed with exit code 128"

### DISCUSSION THREAD

**Discussion by andybeet** [JamesIves/github-pages-deploy-action#1624] [Q&A] [answered]
Dont have a problem running on github.com but using github enterprise on a private repo using a self hosted runner i get an error. Any ideas where to start troubleshooting? Does this suggest git is not configured proprerly? Or does the action not work properly in this environment?

```
name: test ghpages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  getdata:
    runs-on: nefsc-pipeline
    # Only restrict concurrency for non-PR jobs
    # concurrency:
    #   group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: check out repo
        uses: actions/checkout@v4.1.7

      - name: setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          use-public-rspm: true

      - name: install dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build book
        run: Rscript -e 'bookdown::render_book("index.rmd", quiet = TRUE)'
        

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          #TOKEN: ${{ secrets.RTOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _book # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

```

here is the [error](https://github.com/NEFSC/NEFSC-dataserve/actions/runs/9615671840/job/26523422299)
@JamesIves . in case this is a bug or an easy explanation
