### DISCUSSION TITLE
Publishing my documentation in development to Github Pages in another repo

### DISCUSSION THREAD

**Discussion by esparig** [JamesIves/github-pages-deploy-action#1655] [Q&A]
I need help figuring out how to write the GitHub action so it builds my documentation (using Docusaurus) and publishes it in another repo. 

Here is my current GitHub action that triggers when a push to my dev branch is made:

```
# Simple workflow for deploying dev static content to GitHub Pages
name: Deploy dev static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [dev-esparig]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages-dev"
  cancel-in-progress: true

env:
  # Hosted GitHub runners have 7 GB of memory available, let's use 6 GB
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages-dev
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache-dependency-path: '**/package-lock.json'
          cache: npm
      - name: Install dependencies
        working-directory: ./docpage
        run: npm install --frozen-lockfile --non-interactive
      - name: Build
        working-directory: ./docpage
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: ./docpage/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docpage/build
          branch: main
          repository-name: esparig/dcnios-docs
          token: ${{ secrets.GITHUB_TOKEN }}
```

I tried changing the folder, but I always get the error `The directory you're trying to deploy named /home/runner/work/dcnios/dcnios/build doesn't exist`

I'd appreciate the help, thanks.
