### DISCUSSION TITLE
Only a few deploy to gh-pages jobs are successful, cannot lock ref

### DISCUSSION THREAD

**Discussion by SooluThomas** [JamesIves/github-pages-deploy-action#466] [Q&A] [answered]
**Describe the Issue**

I keep getting 
```bash
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
Deployment failed! ❌
```

**Logs**

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/11485594/95898975-d5803180-0d5d-11eb-89af-9c22b4ff01dd.png">

**Additional Comments**

I have reported this in https://github.com/JamesIves/github-pages-deploy-action/issues/365#issuecomment-665793949

**Comment by JamesIves** [comment]
Please post your workflow

**Comment by SooluThomas** [comment]
```yml
on:
  pull_request:
    branches: [ master ]
  label:
     types: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [de_DE, ja_JP, es_ES]
    if: contains( github.event.pull_request.labels.*.name, 'gh-pages' )
    steps:
    - uses: actions/checkout@v2

    - name: Cancel previous Runs
      uses: everphone-gmbh/cancel-previous-workflows@v5

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U virtualenv setuptools wheel
        pip install -U -r requirements-dev.txt sphinx-intl qiskit
        sudo apt-get install graphviz pandoc
    - name: Build translated Qiskit Docs
      env:
        TRANSLATION_LANG: ${{ matrix.language }}
      run: |
        tools/staging_translated_documentation.sh
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build
        CLEAN_EXCLUDE: '["README.md", "index.html", "qiskit_header.png"]'
        ACTIONS_STEP_DEBUG: true
        SSH: true
```
