### DISCUSSION TITLE
Deploying from github repo instead of npm build step

### DISCUSSION THREAD

**Discussion by quentinv72** [JamesIves/github-pages-deploy-action#488] [Q&A]
Hi,

The `Deploy` job seems to be deploying the build present in the repository instead of the build from the `Install and Build 🔧` job.

This is the YAML I am using:

```
name: GH Pages CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true
```
