### DISCUSSION TITLE
Deploying to external repository, getting access denied

### DISCUSSION THREAD

**Discussion by emmahsax** [JamesIves/github-pages-deploy-action#537] [Q&A] [answered]
Hello.

I'm trying to use this to deploy to an external repository. This is what my workflow yml looks like:
```yaml
    - name: Deploy and Publish Site
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        REPOSITORY_NAME: orgname/destination-github-repository
        BRANCH: main
        FOLDER: _site
        COMMIT_MESSAGE: "Publishing site to orgname/destination-github-repository"
        GIT_CONFIG_EMAIL: 1234567+github-user@users.noreply.github.com
        GIT_CONFIG_NAME: github-user
```

I've made a personal access token for the `github-user` account, and put it as a secret (`DEPLOY_ACCESS_TOKEN`) on the source repository (the repository that this action is running on). I've selected for that access token to have access to private repositories, and the user also has access to the `orgname/destination-github-repository`.

But when the action actually goes to run, the build errors with this:
```
remote: Permission to orgname/destination-github-repository.git denied to github-actions[bot].
```

Why is it trying to deploy as `github-actions[bot]`? I thought I was setting it to use the `github-user` account with the `GIT_CONFIG_EMAIL` setting. How do I force this action to use my `github-user` account and email to commit?

@JamesIves The documentation sort of implies that I can use the `GIT_CONFIG_EMAIL` setting to set which GitHub user is doing the commit, but maybe that's not the case?
