### DISCUSSION TITLE
Getting git error "Reference is not a tree" when pushing to external repository

### DISCUSSION THREAD

**Discussion by stlaperriere** [JamesIves/github-pages-deploy-action#567] [Q&A]
Hi all :wave: 

I'm trying to deploy a folder from repoA to repoB. I keep getting a git error which seems to be about some non-existant commits. I'm not sure what is going on. Here is my config:

```
uses: JamesIves/github-pages-deploy-action@3.7.1
with:
  ACCESS_TOKEN: ${{ secrets.REPO_B_ACCESS_TOKEN }}
  REPOSITORY_NAME: organization/repoB
  BRANCH: gh-pages
  FOLDER: source/html
  TARGET_FOLDER: html
  CLEAN: true
  SINGLE_COMMIT: true
```

Here is the error:

```
Deploying using Access Token… 🔑
Configuring git…
/usr/bin/git init
Initialized empty Git repository in /__w/repoA/repoA/.git/
/usr/bin/git config user.name myUserName
/usr/bin/git config user.email 32495334+myUserName@users.noreply.github.com
/usr/bin/git remote rm origin
fatal: No such remote: 'origin'
Attempted to remove origin but failed, continuing…
/usr/bin/git remote add origin https://***@github.com/organization/repoB.git
/usr/bin/git fetch --no-recurse-submodules
From https://github.com/organization/repoB
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      master     -> origin/master
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads https://***@github.com/organization/repoB.git gh-pages | wc -l
2f670ffe7ad580b8e21c662da894286d35ab4506	refs/heads/gh-pages
/usr/bin/git checkout --progress --force a2af1c21b993ea9d91265db4668f8eb3557214bf
fatal: reference is not a tree: a2af1c21b993ea9d91265db4668f8eb3557214bf
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code 128
Deployment failed! ❌
```

Does anyone what could cause this? Is my configuration correct?

**Comment by Pike** [comment]
Can you give https://github.com/JamesIves/github-pages-deploy-action/tree/releases/v4 a try?

We removed all check-out logic, which is probably the functionality breaking here.

The release branch isn't fully up-to-date with the upcoming release, but it should be close, renamings of params aside.

**Comment by joepb** [comment]
I had the same error and now tried with the latest beta but get a similar error:

```
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name myusername
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

my action config now is

```
- name: Deploy 🚀
  uses: JamesIves/github-pages-deploy-action@4.0.0-beta-03
  with:          
    repository-name: mygroup/myrepository
    token: ${{ secrets.PUSH_TOKEN }}
    branch: master
    folder: www
    clean: true
```

Any help is *much* appreciated

**Reply by JamesIves** [reply]
What does your entire workflow look like?

**Comment by Pike** [comment]
I can see how we broke that in a new way for v4.

Would it be possible for you to rewrite your workflow to have your target repository as main checkout repo? That'd help to see if we broke more things.

If that'd work, my ad-hoc idea to fix cross-repo pushes would be to replace `repository-name` with a `workdir` parameter, where the deploy action would expect the checkout of the target repo to be.

**Reply by joepb** [reply]
I don't fully understand what you are asking me to try. 
You mean to deploy it within the same repo as the one I'm checking out? 

The whole purpose is to push it across to another repository. That's basically all the action is supposed to do...

**Reply by joepb** [reply]
I managed to fix is with another package. I know it doesn't help as I'm not using this one anymore.
Just so you can compare if you want to:
```
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
        with:
          source-directory: 'www'
          destination-github-username: 'my-user'
          destination-repository-username: 'my-org'
          destination-repository-name: 'my-repository'
          user-email: my@email.address
```

**Comment by ucefkh** [comment]
same issue


fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree

**Comment by colintheshots-meetup** [comment]
I am also facing this issue.

```
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads https://***@github.com/org/repo.git gh-pages | wc -l
d771012bed64995a10b5e1ef0681828bf87ec312	refs/heads/gh-pages
/usr/bin/git checkout --progress --force 2951204f676ac846d8b74e43dd4ae91bd7aee755
fatal: reference is not a tree: 2951204f676ac846d8b74e43dd4ae91bd7aee755
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code 128
```

Our Github Action
```
name: Generate Dokka Documentation

on: workflow_dispatch

env:
  USERNAME: ${{ secrets.username }}
  EMAIL: ${{ secrets.email }}
  GH_GRADLE_ENTERPRISE_KEY: ${{ secrets.GH_GRADLE_ENTERPRISE_KEY }}

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Build documentation
        run: ./gradlew dokkaHtml

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/dokka/html
```
