### DISCUSSION TITLE
Version 4 Migration Guide

### DISCUSSION THREAD

**Discussion by JamesIves** [JamesIves/github-pages-deploy-action#592] [Releases]
There are a number of breaking changes introduced with version 4 that you should be aware of when migrating your version 3 workflows to version 4. If you have any issues or questions please leave a note before and I'll do my best to help. If you think you've discovered a bug please [open an issue](https://github.com/JamesIves/github-pages-deploy-action/issues).

# General
* All inputs should now be lower cased using kebab casing. If your previous input was `GIT_CONFIG_NAME` it should now be `git-config-name`.

* `PRESERVE` and `LFS` have been deprecated.

* The `clean-exclude` input has had a syntax change. It's now a multiline string with eachline representing the file or folder you'd like to exclude.

```yml
# Version 3
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@3.7.1
   with:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      BRANCH: gh-pages 
      FOLDER: build
      CLEAN: true
      CLEAN_EXCLUDE: '["filename.js", "folder"]'

# Version 4
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@4.0.0
   with:
      token: ${{ secrets.ACCESS_TOKEN }}
      branch: gh-pages 
      folder: build
      clean: true
      clean-exclude: |
         special-file.txt
         some/*.txt
```

# Tokens
* Both `ACCESS_TOKEN` and `GITHUB_TOKEN` inputs are deprecated and can no longer be used. If you used either of these deployment tokens you can now pass either in as `token`.  If you used a GitHub token previously you can also omit `token` from your workflow entirely as that's the default value of the field now.

```yml
# Version 3
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@3.7.1
   with:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      BRANCH: gh-pages 
      FOLDER: build

# Version 4
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@4.0.0
   with:
      token: ${{ secrets.ACCESS_TOKEN }}
      branch: gh-pages 
      folder: build
```

* `SSH` has been replaced with `ssh-key`. If you use another action to setup your SSH client you can set this value to `true`. You can also now pass in an SSH private key as a secret with a pairing repository deployment key and the action will set it up for you. For more details please check out the [README](https://github.com/JamesIves/github-pages-deploy-action/tree/dev-v4#using-an-ssh-deploy-key-).

```yml
# Version 3
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@3.7.1
   with:
      SSH: true
      BRANCH: gh-pages 
      FOLDER: build

# Version 4
- name: Deploy 🚀
   uses: JamesIves/github-pages-deploy-action@4.0.0
   with:
      ssh-key: true # Can also be set to ${{ secrets.DEPLOY_KEY }}
      branch: gh-pages 
      folder: build
```
