### DISCUSSION TITLE
gh-pages deployment issue, job duplicates directory name and fails

### DISCUSSION THREAD

**Discussion by nikonov91-dev** [JamesIves/github-pages-deploy-action#608] [Q&A] [answered]
gh-pages deployment fails with next error: [My repository failed job][5] 
```
Checking configuration and starting deployment… 🚦
Error: The directory you're trying to deploy named /home/runner/work/azure-flask-react/azure-flask-react/dist doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
Deployment failed! ❌
```

[![duplicated directory path in gh-pages job][1]][1]

I'm trying to deploy *ReactApp at Github and besides deploy Python-Flask backend* hosted at Azure and back-app has its automatically *generated job yml*. 

But for front-app I followed [this answer][2] and manually added second job in yml because I need to provide env.variables.

My backend deployment succeeds but front-app constantly fails because of duplicated path 
*/home/runner/work/**azure-flask-react**/**azure-flask-react**/dist*

[Here is my yml][3] and [package.json][4] but there is no any extra mentioning of that directory...
```
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - first-py-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm --prefix front-app install
          npm --prefix front-app run-script build
        env:
          REACT_DEV_SERVER_URL: ${{ secrets.REACT_DEV_SERVER_URL }},
          REACT_DEV_FRONT_APP_URL: ${{ secrets.REACT_DEV_FRONT_APP_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
          BRANCH: gh-pages
          FOLDER: dist

  back-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Build using AppService-Build
        uses: azure/appservice-build@v2
        with:
          platform: python
          platform-version: '3.8'

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'first-py-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7edcdecca83a4354a87943f94bb32fca }}

```
```
{
  ...
  "homepage": "https://nikonov91-dev.github.io/azure-flask-react",
  "scripts": {
    ...
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  },
}

```
and my file structure
```
azure-proj
  |-front-app (containing reactjs)
     |-package.json
     |-node_modules
     |-src
  |-app.py (python-flask application which deploys successfully)

```

  [1]: https://i.stack.imgur.com/Lew4x.png
  [2]: https://stackoverflow.com/questions/53648652/how-to-use-environment-variables-in-github-page
  [3]: https://github.com/nikonov91-dev/azure-flask-react/blob/main/.github/workflows/main_first-py-app.yml
  [4]: https://github.com/nikonov91-dev/azure-flask-react/blob/main/front-app/package.json
  [5]: https://github.com/nikonov91-dev/azure-flask-react/runs/1919880719?check_suite_focus=true

**Comment by JamesIves** [comment, marked as answer]
It's likely that the directory doesn't exist at the root level where the action runs. By the looks of your directory structure you probably need to modify the folder input to be `front-app/dist` as that seems to be where your application gets built. 

```yml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
          BRANCH: gh-pages
          FOLDER: front-app/dist

```

Also two other things to note:

* Use a tagged version of the action, ie `JamesIves/github-pages-deploy-action@3.7.1`, if you point directly to the release branch your workflow will cease to operate if I ever remove or push some broken code to that branch.
* Version 4 is now available, and fixes a lot of issues. You can view the [migration guide here](https://github.com/JamesIves/github-pages-deploy-action/discussions/592). In your case it would be a simple modification to the below step:

```yml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: front-app/dist

```
