### DISCUSSION TITLE
Getting "Error loading key "(stdin)": invalid format" with ssh-key

### DISCUSSION THREAD

**Discussion by bjmiller121** [JamesIves/github-pages-deploy-action#614] [Q&A] [answered]
Hi there,

I'm trying to use this action to deploy to a separate repo and am getting an error during the deploy step. I'm not sure whether I have something misconfigured of I'm just hitting a bug. Any help getting past this error would me much appreciated.

Following the instructions in the README for setting up an SSH key, this is what I've done so far:
1. Generate a new key in terminal via command in README.
2. Add the new key as a Deploy Key in the target repo.
3. Add the new key as a secret with name `DEPLOY_KEY` in the source repo.
4. Add `ssh-key: ${{ secrets.DEPLOY_KEY }}` in my workflow.
5. Run action and have it fail with `Error loading key "(stdin)": invalid format` during the deploy step.

<details>
  <summary>Full readout of deploy step</summary>

```
Run JamesIves/github-pages-deploy-action@4.0.0
  with:
    repository-name: bjmiller121/understory-live
    ssh-key: ***
    branch: gh-pages
    folder: dist
    token: ***
    clean: true

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Configuring SSH client… 🔑
Error loading key "(stdin)": invalid format
Error: The ssh client configuration encountered an error: Command failed: ssh-add -l ❌
(node:2907) UnhandledPromiseRejectionWarning: Error: Command failed: ssh-add -
Error loading key "(stdin)": invalid format

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.0.0/lib/ssh.js:41:37)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.0.0/lib/ssh.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.0.0/lib/ssh.js:4:12)
    at /home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.0.0/lib/ssh.js:40:69
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.0.0/lib/ssh.js:40:55)
(node:2907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2907) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Deployment failed! ❌
```
</details>

<details>
  <summary> My full Worlflow file: deploy-to-ghpages.yml</summary>

```
name: deploy-to-ghpages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install & Build
        run: |
          npm install
          npm run gulp
          npx @11ty/eleventy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: bjmiller121/understory-live
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: dist

```

</details>

Thanks
