### DISCUSSION TITLE
Error: not in a git directory

### DISCUSSION THREAD

**Discussion by rodsan0** [JamesIves/github-pages-deploy-action#651] [Q&A] [answered]
## Describe the bug
Whenever the action runs, we get the error `not in a git directory` and git fails with error code 128. 

## Reproduction Steps

1. Push commit
2. Deploy step eventually fails

## Logs

```
Run JamesIves/github-pages-deploy-action@4.0.0
/usr/bin/docker exec  875f3e7f23a5e2efde6de7fd1004c4d02dd1b3db37a11639fba826e12fccdec5 sh -c "cat /etc/*release | grep ^ID"

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name mmore500
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌

```
[Link to CI.yml](https://github.com/mmore500/dishtiny/blob/master/.github/workflows/CI.yml)

**Comment by JamesIves** [comment]
The likelihood is that the action is not running within the actual folder where the git directory was established. You may need to change directory before running it, or run the checkout step prior which will handle this for you.

**Comment by lezsakdomi** [comment]
I'd like to promote this thread to a bug. This action should also work with empty repositories (i.e. making the initial commit on gh-pages).

I think you should detect if there's already a repository checked out or not, and act accordingly. Or even better, copy the files to the temp folder first, and initialize a new repository in that temp folder afterwards and leave the environmental repository intact.

What if I'd like to use a custom origin, for example?

Here is my hotfix for the problem which also presents a use-case: https://github.com/lezsakdomi/gfp-ring-detector/compare/7e84aa716d3a89e43691523c07c7ff519e458b00...1628d9487fc325d4f25eab83fbdfc7c0fcf11268

**Reply by JamesIves** [reply]
What happens in this workflow if you remove the `--allow-empty` commit and instead just use `git init`? Does it still fail?  I'm interested in creating a fix for this but the answer to that will effect how it gets implemented. 

For this type of workflow you can resolve this in the meantime by running the checkout step before you download the artifacts.

**Reply by lezsakdomi** [reply]
Unfortunately that didn't work either.

CI yml: https://github.com/lezsakdomi/gfp-ring-detector/blob/92eb0a2e36d6b07352ddeb32987054b484ab2faf/.github/workflows/python-app.yml#L75  
CI run URL: https://github.com/lezsakdomi/gfp-ring-detector/runs/6188760712?check_suite_focus=true#step:5:58

Unfortunately it seems like the logs are not public, so I copied them below.

Here are the logs from my step:
```
Run git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/runner/work/gfp-ring-detector/gfp-ring-detector/.git/
```

And from the action:
```
Run JamesIves/github-pages-deploy-action@v4.3.0

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name lezsakdomi
/usr/bin/git config user.email lezsakdomi1@gmail.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
Unable to unset previous git config authentication as it may not exist, continuing…
/usr/bin/git remote rm origin
error: No such remote: 'origin'
Attempted to remove origin but failed, continuing…
/usr/bin/git remote add origin ***github.com/lezsakdomi/gfp-ring-detector.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/lezsakdomi/gfp-ring-detector.git refs/heads/gh-pages
20640aad76445d751a16b1[9](https://github.com/lezsakdomi/gfp-ring-detector/runs/6188760712?check_suite_focus=true#step:5:9)d5c74c72f[20](https://github.com/lezsakdomi/gfp-ring-detector/runs/6188760712?check_suite_focus=true#step:5:20)97675e	refs/heads/gh-pages
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
From https://github.com/lezsakdomi/gfp-ring-detector
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
fatal: invalid reference: HEAD
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/xsu3auos2
Error: The cwd: /home/runner/work/gfp-ring-detector/gfp-ring-detector/github-pages-deploy-action-temp-deployment-folder does not exist!
Notice: Deployment failed! ❌
```

**Reply by lezsakdomi** [reply]
For reference I copy the logs [from the version with initial commit](https://github.com/lezsakdomi/gfp-ring-detector/commit/1628d9487fc325d4f25eab83fbdfc7c0fcf11268) too:

My step:
```
Run git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/runner/work/gfp-ring-detector/gfp-ring-detector/.git/
[master (root-commit) 29d0[7](https://github.com/lezsakdomi/gfp-ring-detector/runs/6189284282?check_suite_focus=true#step:4:7)ca] Initial commit
```

Action output:
```
Run JamesIves/github-pages-deploy-action@v4.3.0

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name lezsakdomi
/usr/bin/git config user.email lezsakdomi1@gmail.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
Unable to unset previous git config authentication as it may not exist, continuing…
/usr/bin/git remote rm origin
error: No such remote: 'origin'
Attempted to remove origin but failed, continuing…
/usr/bin/git remote add origin ***github.com/lezsakdomi/gfp-ring-detector.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/lezsakdomi/gfp-ring-detector.git refs/heads/gh-pages
20640aad76445d751a16b19d5c74c72f2097675e	refs/heads/gh-pages
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
From https://github.com/lezsakdomi/gfp-ring-detector
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 29d07ca)
/usr/bin/git checkout -B gh-pages origin/gh-pages
Previous HEAD position was 29d07ca Initial commit
Switched to a new branch 'gh-pages'
branch 'gh-pages' set up to track 'origin/gh-pages'.
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/gfp-ring-detector/gfp-ring-detector/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github --exclude github-pages-deploy-action-temp-deployment-folder
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/6o1bi14qz
Switched to a new branch 'github-pages-deploy-action/6o1bi14qz'
/usr/bin/git commit -m Deploying to gh-pages from @ lezsakdomi/gfp-ring-detector@162[8](https://github.com/lezsakdomi/gfp-ring-detector/runs/6189284282?check_suite_focus=true#step:5:8)d[9](https://github.com/lezsakdomi/gfp-ring-detector/runs/6189284282?check_suite_focus=true#step:5:9)487fc325d4f25eab83fbdfc7c0fcf[11](https://github.com/lezsakdomi/gfp-ring-detector/runs/6189284282?check_suite_focus=true#step:5:11)268 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/lezsakdomi/gfp-ring-detector.git github-pages-deploy-action/6o1bi14qz:gh-pages
remote: Permission to lezsakdomi/gfp-ring-detector.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/lezsakdomi/gfp-ring-detector.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/6o1bi14qz
Reset branch 'github-pages-deploy-action/6o1bi14qz'
/usr/bin/chmod -R 777 github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code [12](https://github.com/lezsakdomi/gfp-ring-detector/runs/6189284282?check_suite_focus=true#step:5:12)8 ❌
Notice: Deployment failed! ❌
```

**Reply by JamesIves** [reply]
Can you try pointing your workflow to JamesIves/github-pages-deploy-action@releases/v4-init and remove the workarounds and try again?

**Comment by lezsakdomi** [comment]
Hmm it looks like the yml file in the original post was fixed the same approach I used: Creating an initial commit just to fix the action.

**Comment by JamesIves** [comment, marked as answer]
This action more or less depends on `actions/checkout` to run prior to it in order for it to establish the git directory in the workspace. If time permits I can look into implementing a fix for this long term so this isn't necessary, or if someone would like to take this task on I'd be happy to support with reviewing and quality checking the release. For an example of what this might look like you can [click here](https://github.com/JamesIves/github-pages-deploy-action/pull/1101/files), the [contribution guide](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md) will help you get setup. It mostly just need test coverage, but unfortunately I don't have the time at the minute to finish this up. 

```yaml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
```

Alternatively if you use artifacts 

```yaml
name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: windows-latest # The first job utilizes windows-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.

```

If this doesn't resolve the issue for you, please post your logs and try the provided workarounds.
