### DISCUSSION TITLE
fatal: couldn't find remote ref

### DISCUSSION THREAD

**Discussion by RatakondalaArun** [JamesIves/github-pages-deploy-action#702] [Q&A]
I am trying to deploy to GitHub pages but it fails

[workflow file](https://github.com/RatakondalaArun/tmdb_api/blob/ci/docs/.github/workflows/docs.yaml)

```yaml
name: docs

on:
  push:
    branches:
      - master
      - ci/docs

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 📐 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.0

      - name: 🧬 Generate docs
        run: dartdoc --output docs

      - name: 🌳 tree
        run: tree

      - name: 📢 Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs
          folder: docs
```

**logs**

```shell
Run JamesIves/github-pages-deploy-action@4.1.1
  with:
    branch: docs
    folder: docs
    token: ***
    clean: true
  env:
    PUB_CACHE: /home/runner/.pub-cache

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name RatakondalaArun
/usr/bin/git config user.email ratakondalaarun@gmail.com
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/RatakondalaArun/tmdb_api.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/RatakondalaArun/tmdb_api.git docs
d65203b10aff421e431093d440777aa2114a64f4	refs/heads/ci/docs
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin docs
fatal: couldn't find remote ref docs
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code 128
Deployment failed! ❌
```

**Comment by JamesIves** [comment]
I can't seem to reproduce this issue using the following workflow (instead deploying to build, which does not exist at runtime of this).

```
name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run-script build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: build
          folder: build 
```

It's acting as-if the `docs` branch exists and tries to fetch it from the origin, but I can't seem to find it when I look at your [repositories branch list](https://github.com/RatakondalaArun/tmdb_api/branches). If you run `git ls-remote --heads git@github.com:RatakondalaArun/tmdb_api.git docs` in the terminal what do you see? 

Additionally do you have anything else that triggers on the same events? Any other workflows that run in parallel that are accessing git?
