### DISCUSSION TITLE
Action fails with "Cannot delete branch 'master'"

### DISCUSSION THREAD

**Discussion by tsumo** [JamesIves/github-pages-deploy-action#712] [Q&A] [answered]
Hello! First of all - thanks for the action!

I have a little problem. I use this action to update my _username_.github.io from another repository. Here is a snippet from workflow file.

```yaml
- name: Deploy
  uses: JamesIves/github-pages-deploy-action@4.1.2
  with:
    branch: master
    folder: dist
    token: ${{ secrets.PAT }}
    repository-name: tsumo/tsumo.github.io
    target-folder: webgl-study
    commit-message: 'webgl-study (${{ github.event.head_commit.message }})'
```

As you can see I update a single subdirectory in the gh pages repo. It actually works really well, and creates commits as expected, but action itself fails at the end. Here are last lines of the deploy step log

```
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
Resetting branch and removing artifacts…
/usr/bin/git checkout -B github-pages-deploy-action/73l4ld4xu
Switched to a new branch 'github-pages-deploy-action/73l4ld4xu'
/usr/bin/git branch -D master --force
error: Cannot delete branch 'master' checked out at '/home/runner/work/webgl-study/webgl-study'
Error: The process '/usr/bin/git' failed with exit code 1
Deployment failed! ❌
```

I don't understand why it tries to delete master branch in checked-out repo, and I don't know why git complains about it.
