### DISCUSSION TITLE
Exiting early "there is nothing to commit"

### DISCUSSION THREAD

**Discussion by ThatNerdUKnow** [JamesIves/github-pages-deploy-action#737] [Q&A]
I'm trying to deploy my first action to github.io and I thought that using github actions would be a good idea to deploy and build my project to host it on github pages. Here's the message i'm getting on my build
```
Run JamesIves/github-pages-deploy-action@4.1.3

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name Withenex
/usr/bin/git config user.email 32885853+Withenex@users.noreply.github.com
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/Withenex/DnD-BattleTracker.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/Withenex/DnD-BattleTracker.git refs/heads/gh-pages
Creating worktree…
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 59b5b09)
/usr/bin/git checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
Created the gh-pages branch… 🔧
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial gh-pages commit
[gh-pages (root-commit) 31ffeec] Initial gh-pages commit
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/DnD-BattleTracker/DnD-BattleTracker/build/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/524kw28o9
Switched to a new branch 'github-pages-deploy-action/524kw28o9'
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
```

As I understand it, this action should create a branch and build into the build folder then I can have github.io point to that branch and host it but I don't know why it's not wanting to commit

**Comment by JamesIves** [comment]
Can you post your entire workflow please?

**Reply by zh30** [reply]
I also encountered the same problem, this is my configuration, thank you.

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ jamstack ]
  pull_request:
    branches: [ jamstack ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Render
        run: |
          yarn build
          cd out
          cd ..
          
      - name: Debug
        run: |
          ls out
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: 'static' # The branch the action should deploy to.
          folder: 'out' # The folder the action should deploy.
          clean: true
          clean-exclude: '["CNAME", ".nojekyll"]'
```
