### DISCUSSION TITLE
NPM Installation fails

### DISCUSSION THREAD

**Discussion by Paraxdev** [JamesIves/github-pages-deploy-action#780] [Q&A]
I'm using this script:
```yml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.0
      - run: node --version
      - run: npm test
        env:
            CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src/out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
```

It runs fine and downloads everything fine until it runs node & npm I get the error:
`Error: No such file or directory`
this happens either with npm or node basically it doesn't find them? Any ideas what may be wrong?
