### DISCUSSION TITLE
Any push is deploying my website!

### DISCUSSION THREAD

**Discussion by FrightRisk** [JamesIves/github-pages-deploy-action#837] [Q&A] [answered]
I'm trying to learn how actions works and this script. I want people to be able to push to their branch and have the branch build to test is and give an error if there is an issue, but I do NOT want a PUSH or a PR to build and deploy my website. The main branch is called "sphinx". Can anyone help me fix the script so that only when a branch is merged from a PR (or I push directly to the sphinx branch) the website is actually published live? Thank you.

EDIT: I am wondering if just 2 lines surrounded by asterisks will fix it so that any branch that pushes to github will trigger a build to check for errors, but only a push or PR to sphinx (refs/heads/sphinx) will cause a deploy? Commented out the branches line and added the "if". I don't understand how when the PRs were causing a deploy, the sphinx (what we call the master branch) is not updated, but the code from the pushed branch is what is built and pushed to the live site.

```
name: Docs

on:  
  push:
    ****#branches: [ sphinx ]****

  pull_request:
    branches: [ sphinx ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: brew install sphinx-doc
        && brew install enchant
        && pip3 install sphinx-rtd-theme
        && pip3 install sphinx-sitemap
        && pip3 install sphinxcontrib-spelling
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run:  make github
        && echo 'dcc-ex.com' > docs/_build/html/CNAME
        && touch docs/_build/html/.nojekyll
    - name: Deploy
      ****if: github.ref == 'refs/heads/sphinx'****
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
```
