### DISCUSSION TITLE
Lost bullets and +/- expand collapse icons in RTD theme

### DISCUSSION THREAD

**Discussion by FrightRisk** [JamesIves/github-pages-deploy-action#875] [Q&A]
Here is the website: https://dcc-ex.com/

This may be an issue with something that changed in the theme itself, but asking here in addition to their github, Something happened in the last few days that broke at least these 2 things. I am trying to learn how this action works and how RTD works because it seems like a CSS issue. I don't know all the files I should check. From this script and the action, it looks like Github has to download and run code on every build, so I thought something in one of those files it imports changed and that changed the formatting. On my local computer everything is fine since I use these versions:

docutils .16
sphinx 3.3.1
sphinx-rtd-theme 0.5.2
sphinxcontrib-applehelp 1.0.2
sphinxcontrib-devhelp 1.0.2
sphinxcontrib-htmlhelp 1.0.3
sphinxcontrib-jsmath 1.0.1
sphinxcontrib-qthelp 1.0.3
sphinxcontrib-serializinghtml 1.1.4
sphinxcontrib-spelling 7.1.0
in the build log, I can see it uses different versions on GitHub:

Collecting sphinx-rtd-theme
  Downloading sphinx_rtd_theme-1.0.0-py2.py3-none-any.whl (2.8 MB)
Collecting docutils<0.18
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting sphinx>=1.6
  Downloading Sphinx-4.2.0-py3-none-any.whl (3.1 MB)

and this docs.yml

```
name: Docs

on:  
  push:
    ****#branches: [ sphinx ]****

  pull_request:
    branches: [ sphinx ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: brew install sphinx-doc
        && brew install enchant
        && pip3 install sphinx-rtd-theme
        && pip3 install sphinx-sitemap
        && pip3 install sphinxcontrib-spelling
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run:  make github
        && echo 'dcc-ex.com' > docs/_build/html/CNAME
        && touch docs/_build/html/.nojekyll
    - name: Deploy
      ****if: github.ref == 'refs/heads/sphinx'****
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
```
I don't know what other files to check.
