### DISCUSSION TITLE
4.1.6

### DISCUSSION THREAD

**Discussion by JamesIves** [JamesIves/github-pages-deploy-action#931] [Releases]
## Minor Changes
* Resolves an issue that was causing a permission error on the cleanup job. This error was caused by other actions changing directory permissions that prevented a worktree removal step from executing correctly.  #922 
* Migrated the project to Node version 14 across all integration tests, nvm file, etc.
* Numerous third party dependency updates/fixes.
* The `git-config-email` option now accepts an empty string as a valid value in a workflow. This will allow the email part of the commit signature to empty, for example `Author Name <>`.  You can find an example of how to utilize this below. #868 

```yml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: build
          git-config-email: ''
```

<hr /><em>This discussion was created from the release <a href='https://github.com/JamesIves/github-pages-deploy-action/releases/tag/4.1.6'>4.1.6</a>.</em>
