### DISCUSSION TITLE
4.1.7

### DISCUSSION THREAD

**Discussion by JamesIves** [JamesIves/github-pages-deploy-action#939] [Releases]
## Minor Changes
* Dependency upgrades
* Modified README examples to use `npm ci` instead of `npm install` in examples by @bananer in https://github.com/JamesIves/github-pages-deploy-action/pull/934
* Modified the `git-config-email` option again. If you wish to omit this field entirely you must now provide `<>` in the field instead of an empty string. This is due to the fact that GitHub Actions defaults all undefined fields to an empty string, causing the default behavior to not work when you don't provide a `git-config-email` parameter at all. You can find an example of this below.

```yml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: build
          git-config-email: <>
```

## New Contributors
* @bananer made their first contribution in https://github.com/JamesIves/github-pages-deploy-action/pull/934

**Full Changelog**: https://github.com/JamesIves/github-pages-deploy-action/compare/4.1.6...4.1.7

<hr /><em>This discussion was created from the release <a href='https://github.com/JamesIves/github-pages-deploy-action/releases/tag/4.1.7'>4.1.7</a>.</em>
