### DISCUSSION TITLE
How to deploy Github Pages from other branch

### DISCUSSION THREAD

**Discussion by Andision** [JamesIves/github-pages-deploy-action#964] [Q&A] [answered]
I am using this file to build and deploy my Vue.js Project
```
name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - Online
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # 将代码拷贝到虚机中
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
        BRANCH: gh-pages # 存放产物的分支名称
        FOLDER: dist # 存放build后产物的目录
        BUILD_SCRIPT: npm install && npm run build # 执行的命令
```

This script gets source files from the master branch but I'd like to deploy the project on Github Pages from other branch. What should i do to solve this problem? Thank you very much.
