### DISCUSSION TITLE
remote: Invalid username or password.

### DISCUSSION THREAD

**Discussion by SDGPI2020** [JamesIves/github-pages-deploy-action#976] [Q&A] [answered]
## Describe the bug

I'm getting an error when I attempt to commit the master initialize on the Deploy to Github Pages. 

## Logs
Checking configuration and starting deployment… 🚦
Deploying using …… 🔑
Configuring git…
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/data/data/.git/
/usr/bin/git config user.name SDGPI2020
/usr/bin/git config user.email 96308688+SDGPI2020@users.noreply.github.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/PRODUCTION_ORGANISATION/PRODUCTION_REPOSITORY.git
/usr/bin/git fetch --no-recurse-submodules
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/PRODUCTION_ORGANISATION/PRODUCTION_REPOSITORY.git/'
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌

**Comment by JamesIves** [comment, marked as answer]
Please can you provide your workflow file? This is likely occurring due to a change in the GitHub API that disabled a legacy authentication method. Please update your workflow so it points to the latest version as this has been since resolved: `JamesIves/github-pages-deploy-action@4.2.0`. 

Additionally it's a good idea to configure a `.github/dependabot.yml` file with the following so you can get automated pull request updates for your workflows:

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
    open-pull-requests-limit: 10
```
