### DISCUSSION TITLE
Include source commit message in deploy commit message

### DISCUSSION THREAD

**Discussion by curiousdannii** [JamesIves/github-pages-deploy-action#993] [Ideas]
I'd like to be able to include the source commit's message (or the first line at least) in the deploy commit message, so that it says something like

> Deploying to gh-pages from @ 84666d3 🚀 Catch errors for uploaded files, fixes #108

I see that there is a `commit-message` config option, but the docs don't really explain how to use it, so I'm not sure if this sort of customisation would be possible already, or if it would need changes to the action.

**Comment by JamesIves** [comment]
The `commit-message` field allows you to simply override the generated message provided by the action. This is mostly used for integrations that look at specific part of a commit message to make a determination if a followup process should run or not.

The commit message is generated by the action when it processes the build files onto the specified branch. The part after the `@` should link right to the ref that triggered the workflow and will contain the commit messages. At this time there's no way to do what you're asking, but I think this might be worth exploring. [In another project I maintain I've added ways for you to modify things like this with the usage of mustache tags](https://github.com/JamesIves/github-sponsors-readme-action#modifying-the-template-), so perhaps something similar could be done here:

```yml
- name: Deploy 🚀
  uses: JamesIves/github-pages-deploy-action@4.2.0
  with:
    branch: gh-pages
    folder: build
    commit-message: Deploying to {{{ branch }}} from @ {{{ sha }}} 🚀 {{{ message }}}
```

Let me know what you think.
