### DISCUSSION TITLE
deploy file(s), not folder

### DISCUSSION THREAD

**Discussion by nschloe** [JamesIves/github-pages-deploy-action#997] [Ideas]
I have multiple cases where I'd like to deploy a file or files, not a folder; for example, a `README.md`. The following fails:
```yaml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          repository-name: foobar/doc
          branch: main
          folder: README.md
```
with
```
rsync: change_dir "/home/runner/work/foobar/foobar/README.md" failed: Not a directory (20)
```
It seems that the restriction to `folder`s could be lifted to allow for all `path`s, be it folders or files.

**Comment by JamesIves** [comment]
As it stands pushing a single file in this regard isn't supported. Supporting such a thing would be considered a major version bump so there's a few things to consider. 

* If this option did exist, would both `folder` and `files` be merged into a single parameter? Perhaps `paths`?
* Would `paths` accept a single path, or multiple?
* If multiple, what happens when there's a file name conflict in the deployment directory that is created? 
* What if one of the items in the path list is found, but another is not. Does the action fully fail or partially deploy what it could find?

I'm curious to learn more about your use case for this, and if there's a general consensus or not if this is something that multiple people want. 

In the interim you can push `README.md` into a `build` folder by running a script before the deployment job runs, and then simply deploy from the folder that you create within the workflow. 

```yml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate deployment folder
        run: |
          mkdir build 
          mv README.md build/README.md

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          repository-name: foobar/doc
          folder: build # Deploy the newly created "build" folder.
```
