### ISSUE TITLE
Error "There is nothing to commit. Exiting early"

### ISSUE THREAD

**Issue by nsavelyeva** [JamesIves/github-pages-deploy-action#1019]
## Describe the bug

With GitHub workflows I am trying to push `htmlcov` folder [generated for a project in `https://github.com/nsavelyeva/snippman` on an earlier workflow step] into a non-existing directory of a `master` branch in another repository `https://github.com/nsavelyeva/nsavelyeva.github.io` [that is supposed to keep workflow artifacts as github pages].

According to the [documentation](https://github.com/marketplace/actions/deploy-to-github-pages), this is achievable and all parameters that I provide seem to be correct.

## Reproduction Steps
1. Create workflow in one repository - in my case in https://github.com/nsavelyeva/snippman I have [this workflow](https://github.com/nsavelyeva/snippman/blob/enable_veripy_checks/.github/workflows/veripy.yml)
2. Generate some files ready to be pushed - in my case `htmlcov` folder containing HTML report of code coverage
3. Use GitHub Action `JamesIves/github-pages-deploy-action@v4.2.2` to push folder to a non-existing directory of another repository that serves as github pages - in my case to https://github.com/nsavelyeva/nsavelyeva.github.io

```
      - name: Coverage report on GitHub Pages
        if: success() || failure()
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          folder: htmlcov
          repository-name: nsavelyeva/nsavelyeva.github.io
          branch: master
          target-folder: veripy/cov/${{ github.run_id }}/
          git-config-name: ${{ github.event.pusher.name }}
          git-config-email: ${{ github.event.pusher.email }}
          commit-message: Artifacts from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          single-commit: false
```

__Actual result:__ As a result, no files were detected and GitHub Action exited with `There is nothing to commit. Exiting early…`

__Expected result:__ the folder `htmlcov` is successfully pushed to `veripy/cov/${{ github.run_id }}/` folder of `nsavelyeva/nsavelyeva.github.io` repository.

## Logs

```
  with:
    folder: htmlcov
    repository-name: nsavelyeva/nsavelyeva.github.io
    branch: master
    target-folder: veripy/cov/1751466919/
    commit-message: Artifacts from https://github.com/nsavelyeva/snippman/actions/runs/1751466919
    single-commit: false
    token: ***
    clean: true

    GitHub Pages Deploy Action 🚀

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name nsavelyeva
/usr/bin/git config user.email nsavelyeva@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/nsavelyeva/nsavelyeva.github.io.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/nsavelyeva/nsavelyeva.github.io.git refs/heads/master
Creating worktree…
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD fd2383c)
/usr/bin/git checkout --orphan master
Switched to a new branch 'master'
Created the master branch… 🔧
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial master commit
[master (root-commit) bcc9d40] Initial master commit
Creating target folder if it doesn't already exist… 📌
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/snippman/snippman/htmlcov/. github-pages-deploy-action-temp-deployment-folder/veripy/cov/1751466919/ --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/rtb9giod4
Switched to a new branch 'github-pages-deploy-action/rtb9giod4'
/usr/bin/chmod -R 777 github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
```

## Workflow

Workflow links: 
- [execution](https://github.com/nsavelyeva/snippman/runs/4953265446?check_suite_focus=true)
- [snippet](https://github.com/nsavelyeva/snippman/blob/enable_veripy_checks/.github/workflows/veripy.yml) - most of the irrelevant content is commented out there, please ignore it.

## Additional Comments
- I went through https://github.com/JamesIves/github-pages-deploy-action/issues/807 and also tried with and without `single-commit` - same effect.
- I have tried an older version `JamesIves/github-pages-deploy-action@3.7.1`, and it [discovered the files successfully](https://github.com/nsavelyeva/snippman/runs/4952808207?check_suite_focus=true) - most probably because it detected files and treated them as to be deleted. But this old version does not have all the options I need and it pushed files to the master branch of the current repository (luckily we have `git revert` :).

**Comment by JamesIves** [comment]
Thanks for the report. I'll do some research on this tomorrow morning and get back to you once I have some details to share.

**Comment by JamesIves** [comment]
I spent a couple of hours looking into this today and the deeper I get on this issue the more confused I become. From what I can tell the `htmlcov` directory is ignored from the git process somehow which is why it keeps saying there's nothing to commit. If you modify your workflow to generate this directory outside of the veripy action it will work. On the contrary if I modify the `git add` command to use the force flag it works, which makes sense as leveraging -f in this circumstance forcefully ignores anything set in the gitignore config.

```yml
name: veripy
on:
  push:
    branches:
      - main

jobs:
  covgate:
    name: Unit tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: View files
        if: always()
        run: |
          mkdir htmlcov
          cd htmlcov
          touch example.txt

      - name: Coverage report on GitHub Pages
        if: success() || failure()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov
          target-folder: veripy/cov/${{ github.run_id }}/
          repository-name: JamesIves/special-octo-bassoon
          branch: master
          token: ${{ secrets.PAT }}
          git-config-name: ${{ github.event.pusher.name }}
          git-config-email: ${{ github.event.pusher.email }}
          commit-message: Artifacts from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          single-commit: false
          silent: false
```

Is it possible that veripy is adding these generated directories in a way that git is unable to read them and their contents? Either via a globally set git ignore configuration, or perhaps the folder permissions are not adequate enough that git has read access to them? The deployment step is reading/seeing the files, but git for whatever reason is not so it doesn't finish.

I've tried to reproduce this as much as possible and I keep coming back to something within veripy being the culprit but it's pretty difficult to pinpoint what exactly. I've tried using multiple different static site generators under the exact same conditions and in each scenario the deployment seems to pass 😞
