### ISSUE TITLE
Force pushing risks losing data

### ISSUE THREAD

**Issue by rossjrw** [JamesIves/github-pages-deploy-action#1052]
It looks like this action implements its changes by force-pushing to the target branch:

https://github.com/JamesIves/github-pages-deploy-action/blob/226f2c44b58c32b6f07f5835346633e66fc069db/src/git.ts#L220-L221

I believe this works for the vast majority of use cases, but not all of them. In the case where two deployments to different locations on the same branch are initiated at the same time (or perhaps just very close to each other), changes could be destroyed.

<details>
<summary><b>Details about my specific use case</b></summary>

Consider a use case where this action is being used to create multiple deployments in different directories in a single branch - for example, a main `gh-pages` deployment and a preview deployment for a pull request:

```
branch: gh-pages
/
├─ pr-preview/
│  └─ pr-8/
│     └─ <preview deployment>
└─ <main deployment>
```

This repository would have one workflow that creates the main deployment on push to the main branch:

```yml
# .github/workflows/deploy.yml
name: build
on:
  push:
    branches: [main]
jobs:
  deploy:
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean-exclude: pr-preview/
```

And another that handles preview deployments for pull requests - both setting them up for `opened`/`closed`/`synchronize` events, and removing them on `closed` events:

```yml
# .github/workflows/preview.yml
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    if: github.event.pull_request.action != 'closed'
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          target-folder: pr-preview/pr-${{ github.event.pull_request.number }}
  remove-preview:
    if: github.event.pull_request.action == 'closed'
    steps:
      - run: echo "empty_dir=$(mktemp -d)" >> $GITHUB_ENV
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.empty_dir }}
          target-folder: pr-preview/pr-${{ github.event.pull_request.number }}
```

This is where the action's current assumption that all deployments will neatly overwrite the previous deployment breaks down. When a pull request is merged to the main branch, the pull request's `closed` event and the main branch's `push` event will fire at the same time. This causes two simultaneous deployments.

Both deployments will pull and secure a reference to the current SHA of the `gh-pages` branch. They'll prepare their commit, and then push. Normally, one would be successful and the other would fail, but in this case both force-push their changes and one of the commits will be destroyed.

In my case, I merged a pull request, the preview for the pull request was successfully removed, and the main deployment was lost.

</details>

I believe this could be resolved by changing how the action pushes its changes. Rather than force-push the deployment, I think it should attempt a regular push then, if that fails, pull the remote and push again just like a human would.

An implementation that does this forever until it pushes successfully could look something like this:

```js
let rejected
do {
  let pushResult = await execute(
    `git push --porcelain ${action.repositoryPath} ${temporaryDeploymentBranch}:${action.branch}`
  )
  rejected = pushResult.includes(`[rejected]`)
  if (rejected) await execute(
    `git pull --rebase --no-edit ${action.repositoryPath} ${action.branch}:${temporaryDeploymentBranch}`
  )
} while (rejected)
```

Do you think this would work / is a good idea? Have I misdiagnosed the issue; or is there a better way of resolving it?

I'm happy to work on this as a PR - I need this functionality, so I'll be mucking about in a fork regardless. Please do let me know if you have any thoughts.
