### ISSUE TITLE
Github pages action: fatal: not in a git directory

### ISSUE THREAD

**Issue by felixperezc** [JamesIves/github-pages-deploy-action#1083]
## Describe the bug

Github page action: Doesn't work..

## Logs

Run JamesIves/github-pages-deploy-action@4.2.0
/usr/bin/docker exec xxxx sh -c "cat /etc/*release | grep ^ID"

    GitHub Pages Deploy Action 🚀

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es/

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
The operating system you're using is not supported and results may be varied. Please refer to the documentation for more details. ❗
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name xxx
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 1[28] ❌
Deployment failed! ❌
## Workflow

- name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build/docs

**Comment by JamesIves** [comment]
Please provide relevant logs and workflow examples

**Comment by dev-zero** [comment]
Since we're seeing the same issue over at https://github.com/cp2k/dbcsr, here's our workflow definition:

```
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cp2k/dbcsr-build-env-ubuntu-20.04:develop
      volumes:
      - "/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake -G Ninja \
          -DUSE_MPI=ON \
          -DUSE_OPENMP=ON \
          -DUSE_SMM=libxsmm \
          -DMPI_EXECUTABLE_SUFFIX=.mpich \
          ..

    - name: Build
      run: |
        cmake --build build -- doc
        touch build/doc/.nojekyll

    - name: Deploy Development Documentation
      if: github.repository == 'cp2k/dbcsr' && github.ref == 'refs/heads/develop'
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: build/doc
        target-folder: develop
        clean: true
        clean-exclude: |
          releases/
        ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
```
