### ISSUE TITLE
Fatal authentication error during build

### ISSUE THREAD

**Issue by iwiedenm** [JamesIves/github-pages-deploy-action#11]
**Describe the bug**

GitHub action step fails and logs this error: 
`fatal: could not read Password for 'https://***@github.com': No such device or address`

**Reproduce**
I am using this configuration for the action in my workflow.yml:
```
name: Build & Jekyll

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - name: Jekyll build
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{secrets.GH_AUTH_TOKEN}}
          BRANCH: master
          FOLDER: "."
          CNAME: template.itwcreativeworks.com
```
And I have double checked that my GitHub access token is stored as a secret named `GH_AUTH_TOKEN`.

**Expected behavior**

Should build without an error
