### ISSUE TITLE
The process 'git' failed with exit code 128

### ISSUE THREAD

**Issue by uniibu** [JamesIves/github-pages-deploy-action#111]
**Describe the bug**

> The action throws an error `The process 'git' failed with exit code 128`

**Reproduce**

> Simply by deploying to a custom branch

**Logs**

```
git init
Reinitialized existing Git repository in /home/runner/work/redacted/redacted/.git/
git config user.name redacted
git config user.email redacted@redacted.io
git ls-remote --heads https://***@github.com/redacted/redacted.git staging | wc -l
9060ab1802d8825270a2dd031f97c34ad99e4153	refs/heads/staging
git switch master
Switched to a new branch 'master'
M	components/redacted/redacted.vue
Branch 'master' set up to track remote branch 'master' from 'origin'.
git fetch origin
fatal: could not read Username for 'https://github.com': No such device or address
The deployment encountered an error. ❌
##[error]The process 'git' failed with exit code 128
Completed Deployment ✅
##[error]Node run failed with exit code 1
```

**Additional Comments**

> This is due to `git fetch origin` change from the last update
> Pinning our workfile to use 3.1.1 fixes this.

**Comment by JamesIves** [comment]
Can you post a link to your workflow file? Is this sourcing from a scheduled job?

**Comment by uniibu** [comment]
Here is a copy of our .yml file (with some info removed).. This is the current working one as you can see I've pinned it to `3.1.1`, using `releases/v3` (which uses the 3.1.2) is when the error above happens

```
name: Build Staging

on:
  push:
    branches:
      - master

jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-staging-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-staging-${{ hashFiles('**/yarn.lock') }}
      - run: pip install dump-env
      - run: $HOME/.local/bin/dump-env --template=.env.template --prefix='STAGING_' > staging.env
        env:
          STAGING_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          STAGING_SENTRY_DSN: ${{ secrets.SENTRY_DSN_STAGING }}
          STAGING_ISDEBUG: true

      - run: yarn
      - run: yarn build:staging
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@3.1.1
        with:
          CLEAN: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: staging # The branch the action should deploy to.
          FOLDER: dist/ # The folder the action should deploy.
```

**Comment by JamesIves** [comment]
Gotcha - Can you give this a try? `uses: JamesIves/github-pages-deploy-action@releases/v3-test` - I've pushed up a fix for this and will promote it to production if everything works well for you.

**Comment by uniibu** [comment]
`@releases/v3-test` works perfect

**Comment by JamesIves** [comment]
@uniibu If you have a chance, can you test this one last time for me? I pushed up an additional change and want to make sure it still works for you. In my test environment all use cases seem to work but I want to be sure.

**Comment by azangru** [comment]
I am having the same problem with v3, but when I tried v3-test, i got:

```
Run JamesIves/github-pages-deploy-action@releases/v3-test
##[error]You must provide the action with either a Personal Access Token or the GitHub Token secret in order to deploy.
```

My yaml config is as follows:

```
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3-test
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: _site
```

Not sure what's going on.

**Comment by DalderupMaurice** [comment]
I've had the same issue with the following config:
```
name: deploy_web
on:
  pull_request:
    branches:
      - develop
jobs:
  deploy_web:
    name: Deploy on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12.x']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1.3.0
      with:
        node-version: ${{ matrix.node_version }}
    - name: yarn install
      run: yarn install
    - name: yarn compile
      run: yarn compile
    - name: yarn build:web
      run: yarn build:web
    - name: GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.1.2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: packages/web/build
        CLEAN: true
```

I can confirm that the v3-test branch works.
However, I have the option "clean" and the branch doesn't seem to update on my trigger. 
It gives the following message: `There is nothing to commit. Exiting... ✅`

Is there also any update on the use of GITHUB_TOKEN instead of ACCESS_TOKEN?

**Comment by JamesIves** [comment]
If `ACCESS_TOKEN` isn't set up, then try removing it from the configuration. You shouldn't need to have both present and it's likely flagging an incorrect setup because of it.

**Comment by azangru** [comment]
@JamesIves I can confirm that the newly released action works :-) Thank you for the quick fix.

**Comment by rjstelling** [comment]
I'm getting this in 3.1.4, has it regressed?

**Comment by DalderupMaurice** [comment]
same here indeed. I set the version to @3 and the issue is back

**Comment by rjstelling** [comment]
I've pinned the version to 3.1.3 and it's working:

`uses: JamesIves/github-pages-deploy-action@3.1.3`

**Comment by JamesIves** [comment]
What error are you getting?

**Comment by JamesIves** [comment]
@rjstelling @DalderupMaurice Please try `releases/v3-test`.

**Comment by JamesIves** [comment]
Please give `releases/v3-test` a try. I'm unsure how to repro this bug as I'm not personally experiencing this problem. I'd love to figure out _what_ is causing this so I can setup an integration test for it.

**Comment by maetthu** [comment]
`releases/v3-test` works for me (source is a private repo), `releases/v3` doesn't.

Workflow config: 

```
name: ads.txt
on:
  push:	
    branches:	
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build ads.txt
      run: |
        mkdir out
        go run main.go > out/ads.txt
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3-test
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: out 
```     

Log of failing releases/v3 run (the deployment actually works and the result pushed to the repository just fine, but the job is marked as failed).

```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    GITHUB_TOKEN: ***
    BRANCH: gh-pages
    FOLDER: out
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.6/x64
git init
Reinitialized existing Git repository in /home/runner/work/ads.txt/ads.txt/.git/
git config user.name maetthu
git config user.email XXXXXXX
git fetch
fatal: could not read Username for 'https://github.com': No such device or address
##[error]There was an error initializing the repository: Error: The process 'git' failed with exit code 128
git ls-remote --heads ***github.com/emgag/ads.txt.git gh-pages | wc -l
1f30878bab85985ff527bc9b468972ffcae60f4a	refs/heads/gh-pages
git checkout --progress --force 0c841f19a1e7dc3d59d3762a2a46a8c71a02bf85
HEAD is now at 0c841f1 Remove Blob Storage Deployment and git-crypt
git fetch ***github.com/emgag/ads.txt.git
From https://github.com/emgag/ads.txt
 * branch            HEAD       -> FETCH_HEAD
git worktree add --checkout gh-action-temp-deployment-folder origin/gh-pages
Preparing worktree (detached HEAD 1f30878)
HEAD is now at 1f30878 Deploying to gh-pages from  12f1a1bed4885fe57e7ff48d6da0ff5e89f0ac5e
rsync -q -av --progress out/. gh-action-temp-deployment-folder --exclude .git --exclude .github
git status --porcelain
 M ads.txt
git add --all .
git checkout -b gh-action-temp-deployment-branch
Switched to a new branch 'gh-action-temp-deployment-branch'
git commit -m Deploying to gh-pages from  0c841f19a1e7dc3d59d3762a2a46a8c71a02bf85 --quiet
git push --force ***github.com/emgag/ads.txt.git gh-action-temp-deployment-branch:gh-pages
To https://github.com/emgag/ads.txt.git
   1f30878..5d3cb1a  gh-action-temp-deployment-branch -> gh-pages
Running post deployment cleanup jobs... 🔧
rm -rf gh-action-temp-deployment-folder
git checkout --progress --force 0c841f19a1e7dc3d59d3762a2a46a8c71a02bf85
HEAD is now at 0c841f1 Remove Blob Storage Deployment and git-crypt
Completed Deployment ✅
##[error]Node run failed with exit code 1
```
