### ISSUE TITLE
action doubles the repository name for finding the folder

### ISSUE THREAD

**Issue by fritzschoff** [JamesIves/github-pages-deploy-action#1111]
## Describe the bug
`/home/runner/work/ui/ui/storybook-static` as you see here, the CI tries to find the folder with `ui/ui` path which is not specify anywhere and I don't know why where it is coming from.

## Reproduction Steps
build storybook to output the files in the root of the directory with the name `storybook-static`. Then use this action in your CI with this config: 
```
   - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
``` 

## Logs
```
Error: The directory you're trying to deploy named /home/runner/work/ui/ui/storybook-static doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
``` 

## Workflow

```
name: Release
on:
  push:
    branches:
      - main
      - next
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

```

**Comment by JamesIves** [comment]
Does referencing 'storybook-static' over './storybook-static' work? They are technically different as the second one will reference the root as opposed to the cloned directory. The checkout action should clone it into a named folder which is the same as the repo name, so ui/ui would be accurate in this case.

**Comment by fritzschoff** [comment]
I created a new yml file and spun up a new flow. 
```
      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder that the build-storybook script generates files.
```
Now it works fine. So I feel like there was an issue running that in the same job as the semantic-release? 
You definitely need to do 'storybook-static'  without the a leading period and slash.

**Comment by prncevince** [comment]
Just got the same thing using v4.3.3 ... & I did not use quotes 🤷‍♂️

Logs:

https://github.com/prncevince/actions/runs/6381864773?check_suite_focus=true#step:3:37

```
Error: The directory you're trying to deploy named /home/runner/work/actions/actions/static doesn't exist. 
Please double check the path and any prerequisite build scripts and try again. ❗
```

workflow:

https://github.com/prncevince/actions/actions/runs/2304813452/workflow

```yaml
name: build-index
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
jobs:
  index:
    runs-on: ubuntu-latest
    concurrency:
      group: ghpages-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Build site
      shell: bash
      run: echo pre-built site  
    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: static
        target-folder: .
        clean: false
```

**Comment by prncevince** [comment]
Also tested a few different path strategies. Getting the double folder for each one:
https://github.com/prncevince/test-github-pages-deploy-action/commits/main

**Comment by prncevince** [comment]
Shame ... lack of checkout fixed that.

```yaml
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
```

**Comment by fritzschoff** [comment]
reopened issue for @prncevince

**Comment by prncevince** [comment]
Well @fritzschoff, I think it works fine with the suggested `./` before the directory.
I added another github action to my [test repo](https://github.com/prncevince/test-github-pages-deploy-action/tree/8c9976b10a8cd904b1fc2081f945b69246ca83cb) to create a nested page site & it seems to work fine.  

I now have no qualms - just was a bit confused with the necessity of the`./` & the double folder happening quite a bit without it ...   

The nested step that worked fine:

```yaml
    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: ./nest
        target-folder: nest
```
