### ISSUE TITLE
Can't deploy to master, but github pages only allows me to use master

### ISSUE THREAD

**Issue by dooleydiligent** [JamesIves/github-pages-deploy-action#112]
I'm able to use the plugin described here: https://github.com/marketplace/actions/deploy-to-github-pages to deploy to the docs branch, docs folder using this configuration:

```
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: docs # The branch the action should deploy to.
        TARGET_FOLDER: docs  
        FOLDER: docs # The folder the action should deploy.
```

However, when I go to the repository "settings" to configure github pages, I'm only allowed 3 options:
1) master branch
2) master branch /docs folder (*** This is what I've selected)
3) None (disable github pages)

When I use the above configuration the "docs" branch  "docs" folder is updated and I can see the full build information (which is only two folders and the index.md) when browsing the git repo.  However I can only see the index.md file from the url here: https://dooleydiligent.github.io/unit-redis-ness/  The index.md is also in the master branch, docs folder.  But neither of the two referenced directories are in master - only in the docs branch.  So it seems as if the github pages are being served from the master branch, docs folder

If I change the configuration to use 

BRANCH: master

The publish does not occur and I see this in the logs:

```
Run JamesIves/github-pages-deploy-action@releases/v3
git init
Reinitialized existing Git repository in /home/runner/work/unit-redis-ness/unit-redis-ness/.git/
git config user.name <my user name>
git config user.email <my email>
git ls-remote --heads https://***@github.com/dooleydiligent/unit-redis-ness.git master | wc -l
938025fc9bdcc7a7186d3c683284bfda93f18f85	refs/heads/master
git checkout --progress --force 938025fc9bdcc7a7186d3c683284bfda93f18f85
HEAD is now at 938025f Publish to master/docs
git fetch origin
git worktree add --checkout gh-action-temp-deployment-folder origin/master
Preparing worktree (detached HEAD 938025f)
HEAD is now at 938025f Publish to master/docs
rsync -q -av --progress docs/. gh-action-temp-deployment-folder/docs --exclude .git --exclude .github
git status --porcelain
There is nothing to commit. Exiting... ✅
Completed Deployment ✅
```

> Please provide your deployment logs and a link to your workflow file.
Current workflow is:
https://github.com/dooleydiligent/unit-redis-ness/blob/master/.github/workflows/nodejs.yml

**Additional Comments**
Maybe not relevant, but I see something different if I append "/docs" to the url

https://dooleydiligent.github.io/unit-redis-ness/docs/
is different from 
https://dooleydiligent.github.io/unit-redis-ness/

Thanks for your time

**NOTE:  Until I can figure this out I'll just commit the static data directly to the master/docs folder, but I'd really rather not keep it part of the source code branch **

**Comment by uniibu** [comment]
Create a branch first named `gh-pages` onces the branch exists, you can select it on the settings dropdown for github pages

**Comment by dooleydiligent** [comment]
Thanks.  I did that and was able to select the gh-pages branch.  So I updated the config to publish to branch gh-pages/docs and  I still get **There is nothing to commit** when I triggered the build with a push to master
```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    ACCESS_TOKEN: ***
    BRANCH: gh-pages
    TARGET_FOLDER: docs
    FOLDER: docs
  env:
    CI: true
git init
Reinitialized existing Git repository in /home/runner/work/unit-redis-ness/unit-redis-ness/.git/
git config user.name dooleydiligent
git config user.email 59544781+dooleydiligent@users.noreply.github.com
git ls-remote --heads https://***@github.com/dooleydiligent/unit-redis-ness.git gh-pages | wc -l
b7079026177ff08a59bbf575b7632a119c2048b5	refs/heads/gh-pages
git checkout --progress --force 9bb06a179611af15457d9aa300f8751e75e842b7
HEAD is now at 9bb06a1 Still trying to publish
git fetch origin
git worktree add --checkout gh-action-temp-deployment-folder origin/gh-pages
Preparing worktree (detached HEAD b707902)
HEAD is now at b707902 Publish to gh-pages
rsync -q -av --progress docs/. gh-action-temp-deployment-folder/docs --exclude .git --exclude .github
git status --porcelain
There is nothing to commit. Exiting... ✅
Completed Deployment ✅
```

**Comment by JamesIves** [comment]
When you're deploying this are you actually making a change to the documentation? This is a fail-safe that prevents the same files being committed unnecessarily. 

Looking at your project it looks like your static documentation gets built into the `docs/doc` directory, and in your configuration you're deploying the entire `docs` folder, which means GitHub pages doesn't realize there's a static page there as there's no HTML for it to render. Try changing your configuration to the following:

```yml
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: docs
        FOLDER: docs/doc
        CLEAN: true ## Technically you don't need this as you don't generate hashed files, but it's probably a good idea to run it at least on the first deploy.
```

Let me know if that helps.
