### ISSUE TITLE
Using GitHub environment variable as "folder" parameter fails

### ISSUE THREAD

**Issue by matsev** [JamesIves/github-pages-deploy-action#1121]
## Describe the bug

Specifying the `folder` property of `github-pages-deploy-action` as a GitHub Actions environment variable results in an error.

## Reproduction Steps

Configure a workflow where the `folder` property is defined using an environment variable, see below.

*expected result:*
the generated files should be deployed to GitHub pages

*actual result:*
```
Checking configuration and starting deployment… 🚦
Error: The directory you're trying to deploy named /__w/c4-model-adoc/c4-model-adoc/${DEPLOY_DIR} doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
Notice: Deployment failed! ❌
```

## Workflow

```
jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      BUILD_DIR: target
      DEPLOY_DIR: _site

    steps:
      # build steps omitted 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: public
          folder: ${DEPLOY_DIR}
```

## Additional Comments

replacing the `${DEPLOY_DIR}` with the hardcoded value works as expected, e.g.
```
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: public
          folder: _site
```
