### ISSUE TITLE
The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌

### ISSUE THREAD

**Issue by liby** [JamesIves/github-pages-deploy-action#1139]
## Describe the bug

Git error during deployment

## Reproduction Steps

1. Push the code
2. Run CI
3. See error

## Logs

[issue.log](https://github.com/JamesIves/github-pages-deploy-action/files/8895932/issue.log)

## Workflow

```
name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
        with:
          dest: www
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          git-config-name: Bryan Lee
          git-config-email: <>
          repository-name: liby/notes
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: www
          single-commit: true
          commit-message:
          clean: true
          silent: true
```

## Additional Comments

Before triggering this error, I did the following locally:
```
rm -rf .git
git init
git commit -m "xxx"
git remote add origin ...
git push --all --force
```

It seems that an error occurs when there is Git LFS setting in the project. When I remove Git LFS from the project, [it works fine](https://github.com/liby/liby/actions/runs/2492585336).

**Comment by JamesIves** [comment]
I believe you need to enable `lfs` on `actions/checkout` step. Based on the logs it looks like it's failing there. 

```yml
 - uses: actions/checkout@v3
   with:
      lfs: true
```

docs: https://github.com/actions/checkout
