### ISSUE TITLE
Regular git warning causes build failure

### ISSUE THREAD

**Issue by zml2008** [JamesIves/github-pages-deploy-action#1167]
## Describe the bug

It seems like any output to stderr, including output that may be entirely normal, such as lines like

> Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.

will cause this action to [fail the actions build](https://github.com/JamesIves/github-pages-deploy-action/blob/e8f5095e8b3af3fe1ccbf3c02eb56828c3f0975d/src/git.ts#L313=). The build should only be failed when the actual git operation fails.

## Reproduction Steps

Unsure what exact conditions can trigger this issue -- but anything causing git to produce output on stderr without a push failure would trigger this issue

## Logs
See
https://github.com/SpongePowered/math/runs/7374387288?check_suite_focus=true#step:11:59

## Workflow

The relevant use of this action is:

```yaml
      - name: Publish Javadoc
        if: "${{ runner.os == 'Linux' && ((env.STATUS != 'release' && inputs.publish_snapshot_javadoc && github.event_name == 'push' && steps.branch-name.outputs.match != '') || (env.STATUS == 'release' && github.event_name == 'release')) }}"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/publish-jd
          ssh-key: "${{ secrets.SPONGE_JD_DEPLOY_KEY }}"
          repository-name: SpongePowered/APIJavadocs
          branch: data
          git-config-name: Spongie
          git-config-email: staff@spongepowered.org
          clean: false
          force: false
          commit-message: "Publishing javadoc for ${{ github.repository }} ${{ env.PROJECT_VERSION }}"
```

from a workflow shared across the organization

## Additional Comments

n/a
