### ISSUE TITLE
error Couldn't find a package.json file in "..."

### ISSUE THREAD

**Issue by popeindustries** [JamesIves/github-pages-deploy-action#122]
**Describe the bug**

Experiencing the following failure when deploying a `build` folder to `gh-pages` branch (which doesn't yet exist): 

```
error Couldn't find a package.json file in "/home/runner/work/REDACTED-REPO-NAME/REDACTED-REPO-NAME"
##[error]There was an error creating the deployment branch: Error: The process 'git' failed with exit code 1
```

I'm quite lost here, so any help or guidance is appreciated!

~~**edit: could this have something to do with use of [Husky](https://github.com/typicode/husky) git hooks?**~~

**Logs**

Error log:
```
git init
Reinitialized existing Git repository in /home/runner/work/REDACTED-REPO-NAME/REDACTED-REPO-NAME/.git/
git config user.name REDACTED-USERNAME
git config user.email REDACTED-EMAIL
git ls-remote --heads ***github.com/REDACTED-REPO-PATH gh-pages | wc -l
Deployment branch does not exist. Creating....
Creating gh-pages branch... 🔧
git checkout --progress --force 5e08a0dbe7e58c8d05598dac43877b05fe72e3da
HEAD is now at 5e08a0d Add comments
git switch --orphan gh-pages
Previous HEAD position was 5e08a0d Add comments
Switched to a new branch 'gh-pages'

error Couldn't find a package.json file in "/home/runner/work/REDACTED-REPO-NAME/REDACTED-REPO-NAME"
##[error]There was an error creating the deployment branch: Error: The process 'git' failed with exit code 1 ❌

git checkout --progress --force 5e08a0dbe7e58c8d05598dac43877b05fe72e3da
Note: switching to '5e08a0dbe7e58c8d05598dac43877b05fe72e3da'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
  git switch -c <new-branch-name>

Or undo this operation with:
  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5e08a0d Add comments
git fetch ***github.com/nrkno/REDACTED-REPO-NAME.git
From https://github.com/nrkno/REDACTED-REPO-NAME
 * branch            HEAD       -> FETCH_HEAD
git worktree add --checkout gh-action-temp-deployment-folder origin/gh-pages
fatal: invalid reference: origin/gh-pages
The deployment encountered an error. ❌
##[error]The process 'git' failed with exit code 128
Completed Deployment ✅
##[error]Node run failed with exit code 1
```

Workflow file:

```
name: build/deploy

on: push

jobs:
  build_deploy:
    name: Install, lint, and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }} # Cache key based on os + hashed yarn.lock contents

      - name: Yarn install, lint
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn
          yarn lint
      - name: Build
        run: yarn build

      - name: Deploy to gh-pages branch
        if: github.ref == 'refs/heads/master' # Only run if master
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the step should deploy to
          FOLDER: build # The folder the action should deploy
```
