### ISSUE TITLE
The cwd: ****/github-pages-deploy-action-temp-deployment-folder does not exist!

### ISSUE THREAD

**Issue by david072** [JamesIves/github-pages-deploy-action#1255]
## Describe the bug
When attempting to deploy to GitHub pages using version 4.4.1, I'm getting the following error:

```
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/cpuxd9h3k
Error: The cwd: /home/runner/work/axioma/axioma/github-pages-deploy-action-temp-deployment-folder does not exist!
Notice: Deployment failed! ❌
```

## Reproduction Steps
Run a GitHub action job with the configuration below.

## Logs
https://github.com/david072/axioma/actions/runs/3308424503/jobs/5460795727

## Workflow
```
name: Github Pages Experimental

on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        with:
          semver_only: true
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Prepare Build
        run: |
          cargo install cargo-edit -f --no-default-features -F "set-version" &&
          cd gui &&
          cargo set-version "$(echo "${{ steps.bump-semver.outputs.new_version }}" | cut -c2-)-$(git rev-parse --short HEAD)" &&
          cd assets && 
          rm sw.js && rm manifest.json &&
          mv sw_experimental.js sw.js &&
          mv manifest_experimental.json manifest.json
      - name: Build
        run: cd gui && ../trunk build --release --public-url "${GITHUB_REPOSITORY#*/}/experimental"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: gui/dist
          branch: gh-pages
          target-folder: experimental
          single-commit: true
```
