### ISSUE TITLE
'only-if-branch' option

### ISSUE THREAD

**Issue by yegor256** [JamesIves/github-pages-deploy-action#1257]
Would be nice to have `only-if-branch` option:

```
name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: some-very-long-configuration-here
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          only-if-branch: master
```

If this build is running in any other branch except `master` -- the plugin just skips execution.

Without such an option I simply can't reuse the configuration that goes before the action. I have to copy-paste it, which is not elegant at all.
