### ISSUE TITLE
[ERROR] The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌

### ISSUE THREAD

**Issue by 0xmaayan** [JamesIves/github-pages-deploy-action#1285]
## Describe the bug
I have a github workflow that runs the deploy action whenever creating a PR against `main` branch. I noticed that when a contributor creates the PR (who is not admin/codeowner), the deploy action fails with this error - is that expected?
 
<img width="800" alt="Screen Shot 2022-12-13 at 1 19 00 PM" src="https://user-images.githubusercontent.com/29798064/207470132-d1dac1b1-48ea-425e-94d8-16f79b624406.png">

**Comment by endaye** [comment]
```yml
name: GitHub Pages Deploy

on:
  push:
    branches:
      - "dev/en"
env:
  VITE_APP_WALLETCONNECTION_PROJECT_ID: ${{ secrets.VITE_APP_WALLETCONNECTION_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install and bulld
        run: npm i && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
```
I have the same error on v4.4.1 :cry:
