### ISSUE TITLE
`token` not being used sometimes

### ISSUE THREAD

**Issue by provinzkraut** [JamesIves/github-pages-deploy-action#1379]
## Describe the bug

When trying to deploy to a different repo, using the `token` with a PAT, this token does not get picked up by the action sometimes. 

## Reproduction Steps

Unclear since it does not seem to happen every time.

## Logs

Configuration reported for an unsuccessful run: 

```
Run JamesIves/github-pages-deploy-action@v4
  with:
    folder: docs/_build/html
    repository-name: litestar-org/litestar-docs-preview
    clean: false
    target-folder: 1695
    branch: gh-pages
    force: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
    VENV: .venv/bin/activate
```

Configuration reported for a successful run:

```
Run JamesIves/github-pages-deploy-action@v4
  with:
    folder: docs/_build/html
    token: ***
    repository-name: litestar-org/litestar-docs-preview
    clean: false
    target-folder: 1693
    branch: gh-pages
    force: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
    VENV: .venv/bin/activate
```

## Workflow

```yaml
uses: JamesIves/github-pages-deploy-action@v4
with:
  folder: docs/_build/html
  token: ${{ secrets.DOCS_PREVIEW_DEPLOY_TOKEN }}
  repository-name: litestar-org/litestar-docs-preview
  clean: false
  target-folder: ${{ github.event.number }}
  branch: gh-pages
```

## Additional Comments

From the logs it's obvious that the token isn't being used, but I am at a loss as to why that is. The secret hasn't been touched between the runs nor has the workflow file been added. I already checked the PAT permissions and regenerated it but to no avail.
