### ISSUE TITLE
Pushed file asyncapi.html gets renamed to index.html

### ISSUE THREAD

**Issue by oliverunger** [JamesIves/github-pages-deploy-action#1426]
## Describe the bug
The file asyncapi.html I want to push gets renamed to index.html and overwrites the current index.html file.

## Workflow
I have the following workflow:
   ```
   - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.12
        with:
          template: '@asyncapi/html-template@0.28.4'
          filepath: api/src/main/resources/docs/api/my_asyncapi.yml
          outFilename: asyncapi.html
          parameters: singleFile=true
          output: pages

      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          folder: pages
          clean: false
```
The first action creates a file named asyncapi.html.
When the "Deploy GH page" is triggered, it renames this file to index.html and pushes it to the gh-branch.

## Expectation
New file asyncapi.html gets added. Other files already on that branch stay as they are.
