### ISSUE TITLE
A file is missing or not transferred to github pages

### ISSUE THREAD

**Issue by maxkostin** [JamesIves/github-pages-deploy-action#1475]
## Describe the bug

A file is missing from the destination folder: the action is run with no errors, but one file is missing/not transferred to the github pages (_commonjsHelpers-725317a4.js). Setting `clean: false` or `clean: true` makes no difference. When running `npm run build-storybook` locally, all files are there.

## Workflow
```yaml
name: Publish edge version

on:
  push:
    branches:
      - "master"
  pull_request:

concurrency: ${{ github.ref }}

jobs:
  publish:
    name: Publish edge version
    runs-on: ubuntu-latest
    environment: nonprod
    env:
      NODE_AUTH_TOKEN: ${{ secrets.SS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SS }}

      - name: Use node 16 and npm
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com
          scope: myscope
          cache: "npm"

      - name: Install
        run: npm i

      - name: Build, test, quality check
        run: npm run build

      - name: Build strorybook
        run: npm run build-storybook

      - name: Determine new version type (major | minor | patch)
        id: new-version-type
        env:
          COMMIT_MSG: ${{ github.event.commits[0].message }}
        run: |
          NEW_VERSION_TYPE='patch'
          if [[ $COMMIT_MSG == feat:* ]] || [[ $COMMIT_MSG == feat\(* ]];
          then
          NEW_VERSION_TYPE='minor'
          fi
          if [[ $COMMIT_MSG =~ "BREAKING CHANGE" ]];
          then
          NEW_VERSION_TYPE='major'
          fi
          echo "::set-output name=version_type::$NEW_VERSION_TYPE"

      - name: Configure git
        run: |
          git config --global user.email "abc@abc.com"
          git config --global user.name "abc"
          git config --global push.followTags true
          git config --global pull.rebase true

      - name: Bump package.json version in workspace
        id: bump-version
        run: npm version ${{ steps.new-version-type.outputs.version_type }} -m "(chore) bump to version %s [skip actions]"

      - name: Push version commit
        if: github.ref == 'refs/heads/master'
        run: |
          git push

      - name: Publish edge version
        if: github.ref == 'refs/heads/master'
        run: |
          npm publish --tag edge

      - name: Publish stories
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: docs
          folder: storybook-static
          clean: false
```
