### ISSUE TITLE
Problem deploying react app

### ISSUE THREAD

**Issue by Kostu96** [JamesIves/github-pages-deploy-action#165]
The action completes succesfully but "Your site is having problems building: Page build failed." Is notified in repo settings.
This is my yaml for action
```
name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        persist-credentials: false

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build
```
