### ISSUE TITLE
bug: 🐝 action incorrectly reports nothing to commit

### ISSUE THREAD

**Issue by lucascolley** [JamesIves/github-pages-deploy-action#1707]
### Describe the bug

_EDIT: updated to the correct link_

https://github.com/data-apis/array-api-extra/actions/runs/11108938259 shows this action saying that `There is nothing to commit`, when changes were in fact made to the docs.

### Reproduction Steps

see above workflow run

### Workflow

```yml
name: Docs Deploy

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    environment:
      name: docs-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: docs-build.yml
          name: docs-build
          path: docs/build/

      # Note, the gh-pages deployment requires setting up a SSH deploy key.
      # See
      # https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          force: yes
```
