### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FFY00** [JamesIves/github-pages-deploy-action#172]
```yaml
name: Push documentation
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Deploy
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build/html
        BUILD_SCRIPT: pip install hid-tools sphinx sphinx_autodoc_typehints pallets_sphinx_themes recommonmark && cd docs && make && touch build/html/.nojekyll 
```

Workflow run: https://github.com/FFY00/ratbag-emu/runs/448622510

Do you have any idea why this is not working?
