### ISSUE TITLE
Node run failed with exit code 1

### ISSUE THREAD

**Issue by Safnaj** [JamesIves/github-pages-deploy-action#173]
**Describe the bug**
As i refer your blog article trying to deploy an Angular App to GitHub Pages. Here is the Workflow that i am using. Its getting failed because of node failuers. 

```
name: CI

on: [push]

env:  
  NODE_VERSION: '10.x'

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: master
        FOLDER: dist/github-community-sl
        BUILD_SCRIPT: npm install && npm run build -- --prod
```

**Reproduce**
It Should Build the App and Deploy to the same branch.

**Logs**

[https://github.com/GitHubExperts-LK/GitHubExperts-LK.github.io/actions/](https://github.com/GitHubExperts-LK/GitHubExperts-LK.github.io/actions/)

**Additional Comments**

> Add any other context about the problem here.

**Comment by JamesIves** [comment]
I don't have a blog post on this so I'm not sure what instructions you're following, but by the sounds of things they're not in sync with the version you're trying to use. The `BUILD_SCRIPT` parameter has been deprecated since version 2. Please refer to the README for the up-do-date instructions.

By the looks of things you probably need to create an additional step that builds your project. Also your `BRANCH` is pointing to master, if you are intending for the action to deploy to this branch then that's fine, but I'm guessing you want it to be `gh-pages` or `docs`.

```yml

name: CI

on: [push]

env:  
  NODE_VERSION: '10.x'

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

        
    - name: Install
       run: |
          npm install
          npm run-script build -- --prod

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist/github-community-sl
```
