### ISSUE TITLE
bug: 🐝 Cannot create target folder since 4.7.1 on self-hosted runner (`rsync: --mkpath: unknown option`)

### ISSUE THREAD

**Issue by marcus-bcl** [JamesIves/github-pages-deploy-action#1753]
### Describe the bug

Since upgrading to 4.7.1, the deploy action now fails with `rsync: --mkpath: unknown option`.

The `--mkpath` option was added in rsync 3.2.3, but our self-hosted runner (based on https://github.com/myoung34/docker-github-actions-runner) only has 3.1.3.  Do we need to upgrade rsync for this to work or would it be possible for the action to support older versions?

### Reproduction Steps

Use a self-hosted runner with rsync <3.2.3.

### Logs

```shell
/usr/bin/rsync -q -av --checksum --progress --mkpath ... --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
rsync: --mkpath: unknown option
rsync error: syntax or usage error (code 1) at main.c(1601) [client=3.1.3]
```

https://github.com/ministryofjustice/hmpps-probation-integration-e2e-tests/actions/runs/12115120629/job/33776527330#step:12:68

### Workflow

```yml
- name: Publish HTML report
  uses: JamesIves/github-pages-deploy-action@dc18a3c6b46d56484cb63f291becd7ed4f0269b9 # v4
  with:
    folder: folder
    target-folder: target-folder
```

https://github.com/ministryofjustice/hmpps-probation-integration-e2e-tests/actions/runs/12115120629/workflow#L176-L181
