### ISSUE TITLE
CLEAN_EXCLUDE didn't work?

### ISSUE THREAD

**Issue by iRuxu** [JamesIves/github-pages-deploy-action#202]
**Describe the bug**

> When I set the "clean_exclude",but it seems didn't wok. I think the path is based on the gh-pages root? 
```
- name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN_EXCLUDE: '["css", "js"]'
        BUILD_SCRIPT: npm install && npm run build
```
I set like this.
I wanna ignore to delete the css&js files.
But it still clean the whole gh-pages instead.
https://github.com/JX3BOX/jx3box-search/tree/gh-pages/css 
https://github.com/JX3BOX/jx3box-search/tree/gh-pages/js

**Logs**

https://github.com/JX3BOX/jx3box-search/runs/512605002?check_suite_focus=true
```

found 0 vulnerabilities


> jx3box-search@ build /github/workspace
> vue-cli-service build


-  Building for production...
 DONE  Compiled successfully in 5165ms1:00:36 AM

  File                                 Size               Gzipped

  dist/js/chunk-vendors.49518ef6.js    93.84 KiB          32.36 KiB
  dist/js/app.d2261a0d.js              13.72 KiB          5.63 KiB
  dist/css/app.c1ed913a.css            3.59 KiB           1.15 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
Deploying to GitHub...
1/2 (0)
2/2 (1)
To https://github.com/JX3BOX/jx3box-search.git
 + b2787f8...a44f843 a44f843a5e049e19b407810136df812e3bcdefbb -> gh-pages (forced update)
Deployment succesful!
```

Thanks a lot! ❤️

**Comment by JamesIves** [comment]
👋 Hi!

The version of the action you're using is out of date and runs on an older version. Please switch to `JamesIves/github-pages-deploy-action@releases/v3` in your workflow. 

Here's an updated config:

```
- name: Install
     run: |
       npm install
       npm run-script build

- name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        CLEAN_EXCLUDE: '["css", "js"]'
```

You'll also need to add `CLEAN: true` to your config in order to use `CLEAN_EXCLUDE`.

You can find details about this configuration in the [readme](https://github.com/JamesIves/github-pages-deploy-action).

**Comment by iRuxu** [comment]
I switched to `JamesIves/github-pages-deploy-action@releases/v3`
```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
  env:
    ACCESS_TOKEN: ***
    BRANCH: gh-pages
    FOLDER: dist
    CLEAN: true
    CLEAN_EXCLUDE: ["css", "js"]
    BUILD_SCRIPT: npm install && npm run build
Checking configuration and starting deployment...🚦
##[error]There was an error initializing the repository: No deployment token/method was provided. You must provide the action with either a Personal Access Token or the GitHub Token secret in order to deploy. If you wish to use an ssh deploy token then you must set SSH to true. ❌
Deployment Failed ❌
```
https://github.com/JX3BOX/jx3box-search/runs/512708820

**Comment by iRuxu** [comment]
I finnaly fixed this problem.
thank you so much ~❤️

**Comment by manzt** [comment]
I'm having the same issue in this project https://github.com/manzt/vizarr.

```
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run export && touch out/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
          CLEAN_EXCLUDE: '["v0.1"]' # Manually add endpoints to keep
```

I've manually pushed a versioned build of my site to `v0.1`, but when merging master with the above action, this folder gets removed https://github.com/manzt/vizarr/commit/deecebaa45ce464a0ff6ae9ce93e0a9f6da2c6de. Am I missing something?
