### ISSUE TITLE
"There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128"

### ISSUE THREAD

**Issue by iansan5653** [JamesIves/github-pages-deploy-action#250]
**Describe the bug**

I'm trying to deploy a simple React app with a simple configuration but I'm getting this error as soon as I hit the deploy step. Not sure what I'm doing wrong as I copied the configuration from another repo I set up recently and that one is working great.

**Reproduce**
Full workflow file:
```
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy App
    container:
      image: docker://node
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
```
**Logs**

```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    ACCESS_TOKEN: ***
    BRANCH: gh-pages
    FOLDER: build
/usr/bin/docker exec  cd17effc5efebd42cae1c40350c356e53de1056d62fb6c33b209b09940ffd1aa sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
Checking configuration and starting deployment… 🚦
Deploying using Access Token… 🔑
Configuring git…
##[error]There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment Failed ❌
```

**Additional Comments**

I also tried with just the GITHUB_TOKEN as well as with the GITHUB_TOKEN and my custom access token.
