### ISSUE TITLE
I have not config ACCESS_TOKEN in my private repo but it still works, I wonder what's going on, so confused

### ISSUE THREAD

**Issue by Haojen** [JamesIves/github-pages-deploy-action#253]
Here is my config `main.yml`,  as you can see, **I have not config anything ACCESS_TOKEN** , But it does work.
this my steps:
1. commit and push to master branch
2. auto trigger this Action
3. this action run my command: build and deploy to  `gh-pages` 

everything is prefect， Who can tell me what happened ? 

```
name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run install
      run: npm install

    - name: Run build
      run: npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
```
