### ISSUE TITLE
Is there a way to see whether a new commit was made or not?

### ISSUE THREAD

**Issue by emma-sax4** [JamesIves/github-pages-deploy-action#295]
**Describe the Issue**
Is there a way for me to know whether anything was actually committed or not, and then use that programmatically on future steps in the workflow? If the deploy runs and there's no changes to the GitHub Pages site (such as if only documentation was updated), then there's no commit to the `master` branch, then the Actions log shows this as a message that there was nothing to commit:
```
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
There is nothing to commit. Exiting early… 📭
Completed Deployment Successfully! ✅
```

But, I can't figure out a way to use that programmatically as I continue with the workflow.

It would be nice if there was an `output` parameter like described [here](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) or something so we knew if something was committed or not programmatically, and then we could read it `${{ steps.deploy.outputs.status }}` or something.

**Logs**
Here's a link to the log: https://github.com/emma-sax4/emma-sax4.github.io/runs/674942821?check_suite_focus=true (but there was no actual commit to the `master` branch from this run)

Here's a link to my workflow: https://github.com/emma-sax4/emma-sax4.github.io/blob/1e2048db418a53185981e8770a0d382e7841d4da/.github/workflows/test-and-deploy.yml#L44-L51

**Additional Comments**
The reason I would find this useful is because I notify Slack when my GitHub Action workflow is done, and it'd be nice to be able to modify the Slack message based on the status of the GitHub Pages deployment. Something like:
```
Deploy to GitHub Pages status: **${{ steps.deploy.outputs.status }}**.
```
> Deploy to GitHub Pages status: **success**.

or

> Deploy to GitHub Pages status: **skipped**.

or

> Deploy to GitHub Pages status: **failed**.

**Comment by JamesIves** [comment]
I love the idea of this! I think `success|skipped|failed` would work for the outputs too. I'll try and push this up in the release that's coming today.

**Comment by emma-sax4** [comment]
@JamesIves That'd be unbelievably incredible!

**Comment by JamesIves** [comment]
Here's the PR: https://github.com/JamesIves/github-pages-deploy-action/pull/296

I will post again once I make the release.

**Comment by JamesIves** [comment]
@emma-sax4 This is now available as part of `3.5.0`: https://github.com/JamesIves/github-pages-deploy-action#deployment-status

**Comment by emma-sax4** [comment]
This may be silly, but how do I access the variable? I set this as my config with an `id`:
```yml
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      id: deployment
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: _site
        COMMIT_MESSAGE: 'Deploy to ${{ github.repository }}.git:master via GitHub Actions'
        CLEAN_EXCLUDE: '[".git", ".circleci", ".github"]'

    - name: Check status
      run: |
        echo "Status is: ${{ steps.deployment.outputs.DEPLOYMENT_STATUS }}"
```
And the log returns this:
![image](https://user-images.githubusercontent.com/7562793/81990530-f9034c80-9604-11ea-8e54-de8593d8dc37.png)

It looks like this action is saving it as an environment variable? But I'm not sure how to get the `skipped` out as a string.
