### ISSUE TITLE
fatal: No such remote: 'origin'

### ISSUE THREAD

**Issue by jscheid** [JamesIves/github-pages-deploy-action#331]
**Describe the bug**

I'm getting the error `The process '/usr/bin/git' failed with exit code 128`, but I think the root cause is `fatal: No such remote: 'origin'` (see logs below).

**Reproduce**

Not sure, this is what my step looks like:
```yaml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.target_branch.outputs.replaced }}
          BASE_BRANCH: develop
          FOLDER: dist
```

**Logs**

```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    GITHUB_TOKEN: ***
    BRANCH: deploy-develop
    BASE_BRANCH: develop
    FOLDER: dist
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
/usr/bin/git init
Initialized empty Git repository in /home/runner/work/prettier-melpa-test/prettier-melpa-test/.git/
/usr/bin/git config user.name jscheid
/usr/bin/git config user.email redacted@example.com
/usr/bin/git remote rm origin
fatal: No such remote: 'origin'
##[error]There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
```

**Additional Comments**

This uses `runs-on: ubuntu-18.04`, in case it matters.
