### ISSUE TITLE
fatal: No such remote: origin

### ISSUE THREAD

**Issue by andrewc910** [JamesIves/github-pages-deploy-action#350]
**Describe the bug**
Action fails to deploy.

**Reproduce**
Created a deploy.yml file. Copy & pasted the template given in the readme & made minor edits for my coding language. Here is the action file:
```yml
name: Build and Deploy

on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          shards install
          crystal docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.6
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
```

**Logs**
```
Run JamesIves/github-pages-deploy-action@3.5.6
/usr/bin/docker exec  5af2ef841492c1e9b979a4dcaf5769cf08528b6ec8ab0f3bd4887049607cfccc sh -c "cat /etc/*release | grep ^ID"
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
/usr/bin/git init
Initialized empty Git repository in /__w/mochi/mochi/.git/
/usr/bin/git config user.name andrewc910
/usr/bin/git config user.email 49383564+andrewc910@users.noreply.github.com
/usr/bin/git remote rm origin
fatal: No such remote: origin
##[error]There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

**Additional Comments**
My repo: https://github.com/andrewc910/mochi/
I had a travis.yml file that would do the deploy. As i have switched to github actions for CI, i am also switching the deploy. I already have a gh-pages here: https://github.com/andrewc910/mochi/tree/gh-pages
Do i need to delete that one for this action to make a new one? It should be the same file hierarchy and format.
