### ISSUE TITLE
Action does not deploy CNAME or .nojekyll files

### ISSUE THREAD

**Issue by LPGhatguy** [JamesIves/github-pages-deploy-action#354]
I recently started a new project using this action to deploy to GitHub Actions. My page generator [creates `CNAME` and `.nojekyll` files](https://github.com/LPGhatguy/rojo.space-v2/blob/8b3c27248ad1ab4a6dc2b01f10916ecf8e1da2f1/generator.js#L166-L172), but I noticed that [my gh-pages branch](https://github.com/LPGhatguy/rojo.space-v2/tree/037d6d9f56f103a06f700391894917e8ec1f31bc) didn't end up with either of those files!

It appears that, although this action preserves those files if they were already there, it does not add them if they weren't there already. I have since manually added those files by hand. I read [in this repository's README](https://github.com/JamesIves/github-pages-deploy-action#additional-build-files-) that `CNAME` and `.nojekyll` are special, which leads me to believe there may be a bug.

My use of the workflow is:
```yaml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
```

Here is a run of the relevant workflow: https://github.com/LPGhatguy/rojo.space-v2/runs/837921047?check_suite_focus=true

This run happened after I manually added `CNAME` (because I noticed it was missing), but before I manually added `.nojekyll`. There are no error messages or output to report, just this funny behavior.
