### ISSUE TITLE
Docker run failed with exit code 1

### ISSUE THREAD

**Issue by vhoyer** [JamesIves/github-pages-deploy-action#36]
**Describe the bug**

https://github.com/vhoyer/timedReport

```
...
Setting up libjq1:amd64 (1.5+dfsg-1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up jq (1.5+dfsg-1.3) ...
Reinitialized existing Git repository in /github/workspace/.git/
Switched to a new branch 'master'
Branch master set up to track remote branch master from origin.
Running build scripts... 
Deploying to GitHub...
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
Docker run failed with exit code 1
```

**Reproduce**

```yaml
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: src # The folder the action should deploy.
```

Folder struct:
```
.
├── package.json
├── package-lock.json
└── src
    ├── components
    │   ├── card.js
    │   ├── context.css
    │   ├── context.js
    │   └── my-footer.js
    ├── css.css
    ├── index.html
    ├── js.js
    └── resources
        └── body-bg.svg
```

**Expected behavior**

Deploy to gh pages

**Additional Comments**

[logs_10.zip](https://github.com/JamesIves/github-pages-deploy-action/files/3720927/logs_10.zip)
