### ISSUE TITLE
Failed to delete '.../github-pages-deploy-action-temp-deployment-folder': File name too long

### ISSUE THREAD

**Issue by LPGhatguy** [JamesIves/github-pages-deploy-action#364]
It appears that deployment on one of my projects using this action is now failing with an interesting error message:

```
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
error: failed to delete '/home/runner/work/v80.lpg.space/v80.lpg.space/github-pages-deploy-action-temp-deployment-folder': File name too long
##[error]The process '/usr/bin/git' failed with exit code 255
Deployment failed! ❌
```

It is possible that any deployments might hit this right now. The same project was able to deploy before with the same workflow file. This might be a GitHub Actions issue?

* Here is a successful run from earlier today on `releases/v3`: https://github.com/LPGhatguy/v80.lpg.space/runs/870424251
* Here is a run that failed when running on `releases/v3`: https://github.com/LPGhatguy/v80.lpg.space/runs/872114761
* ...and the 3.5.7 tag: https://github.com/LPGhatguy/v80.lpg.space/actions/runs/169613234
* ...and the 3.5.6 tag: https://github.com/LPGhatguy/v80.lpg.space/actions/runs/169615580

Here is the workflow file for all of these runs, even the successful one, is:

```yaml
name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
```

As you can see, these are running on Ubuntu! I didn't realize there was a file length limit, or that it could be as short as 90 characters! 😄 

I'm not sure there's anything you can do about this as an action author. It's possible something changed today on GitHub's end. I'll see if I can repro this in the same project tomorrow, or if anyone else can repro before then.
