### ISSUE TITLE
Add .nojekyll support 

### ISSUE THREAD

**Issue by mitinarseny** [JamesIves/github-pages-deploy-action#38]
Please, add support for adding `.nojekyll` file to `gh-pages` branch. Also, consider #37:
```yaml
uses: JamesIves/github-pages-deploy-action@master
with:
  nojekyll: true
  # ...
```
