### ISSUE TITLE
Support for absolute paths

### ISSUE THREAD

**Issue by yves-chevallier** [JamesIves/github-pages-deploy-action#387]
In my attempt I use previously created artifacts to upload it to gh-pages. To avoid any name collision, the artifacts are downloaded outside from the repository:

```yaml
  deploy:
    name: Deploy on GH-Pages
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ~/download/html
          name: html
      - run: ls -al ~/download/html
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          BRANCH: gh-pages
          FOLDER: ~/download/html
```

Unfortunately this doesn't seem supported:

```
rsync: change_dir "/home/runner/work/handout/handout//~/download/html" failed: No such file or directory (2)
```

One possible workaround is to download my artifacts in a folder with an obscure name: `.this-is-a-folder-that-should-not-exist-in-this-repository`
