### ISSUE TITLE
use REPOSITORY_NAME deploy other repositories fail

### ISSUE THREAD

**Issue by libaibuaidufu** [JamesIves/github-pages-deploy-action#389]
**Describe the Issue**

i want to deploy my other repository from my private repository,but always deploy self's repository for use REPOSITORY_NAME .
this is my workflow.
```
name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        REPOSITORY_NAME: libaibuaidufu/libaibuaidufu.github.io 
        BRANCH: master
        BASE_BRANCH: master
        FOLDER: public 
        BUILD_SCRIPT:  npm install hexo-cli -g && npm install && hexo clean && hexo g  
```

**Logs**

```
...
Setting up jq (1.5+dfsg-1.3) ...
Reinitialized existing Git repository in /github/workspace/.git/
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Running build scripts... npm install hexo-cli -g && npm install && hexo clean && hexo g
.....

Deploying to GitHub...
1/2 (0)
2/2 (1)
To https://github.com/libaibuaidufu/private-blog-deploy-actions.git
 + ac197dd...9c8bcd9 9c8bcd96aa32425cd4916242e72becc31f4022f3 -> master (forced update)
Deployment succesful!
```
**Additional Comments**

## now i update my action version.
```
name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        REPOSITORY_NAME: libaibuaidufu/libaibuaidufu.github.io 
        BRANCH: master # The branch the action should deploy to.
        BASE_BRANCH: master # The branch the action should deploy from.
        FOLDER: public 
        BUILD_SCRIPT:  npm install hexo-cli -g && npm install && hexo clean && hexo g 
```
## new error logs:
```
warning: no common commits
From https://github.com/libaibuaidufu/libaibuaidufu.github.io
 * [new branch]      master     -> origin/master
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads https://***@github.com/libaibuaidufu/libaibuaidufu.github.io.git master | wc -l
cef818f453edc2961dda98d33a74d33444b298d3	refs/heads/master
/usr/bin/git checkout --progress --force master
Already on 'master'
/usr/bin/git fetch https://***@github.com/libaibuaidufu/libaibuaidufu.github.io.git
From https://github.com/libaibuaidufu/libaibuaidufu.github.io
 * branch            HEAD       -> FETCH_HEAD
/usr/bin/git worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/master
Preparing worktree (detached HEAD cef818f)
HEAD is now at cef818f Site updated: 2020-08-05 17:47:31
/usr/bin/rsync -q -av --checksum --progress public/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
rsync: change_dir "/home/runner/work/private-blog-deploy-actions/private-blog-deploy-actions//public" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
##[error]The deploy step encountered an error: The process '/usr/bin/rsync' failed with exit code 23 ❌
Deployment failed! ❌
```

**Comment by libaibuaidufu** [comment]
## now now i update my action workflow
```
name: buildAndDeploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: build
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        REPOSITORY_NAME: libaibuaidufu/libaibuaidufu/private-blog-deploy-actions 
        BASE_BRANCH: master
        BRANCH: gh-pages 
        FOLDER: public 
        BUILD_SCRIPT:  npm install hexo-cli -g && npm install && hexo clean && hexo g
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        REPOSITORY_NAME: libaibuaidufu/libaibuaidufu.github.io 
        BRANCH: master
        BASE_BRANCH: master 
        FOLDER: public 
```
### i want to use npm ,so i use v2 to build hexo,then use v3 to deploy.but permission error.

## error logs
```
...
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/private-blog-deploy-actions/private-blog-deploy-actions/.git/
/usr/bin/git config user.name libaibuaidufu
/usr/bin/git config user.email 32195121+libaibuaidufu@users.noreply.github.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin https://***@github.com/libaibuaidufu/libaibuaidufu.github.io.git
/usr/bin/git fetch --no-recurse-submodules
warning: no common commits
From https://github.com/libaibuaidufu/libaibuaidufu.github.io
 * [new branch]      master     -> origin/master
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads https://***@github.com/libaibuaidufu/libaibuaidufu.github.io.git master | wc -l
cef818f453edc2961dda98d33a74d33444b298d3	refs/heads/master
/usr/bin/git checkout --progress --force master
Already on 'master'
/usr/bin/git fetch https://***@github.com/libaibuaidufu/libaibuaidufu.github.io.git
From https://github.com/libaibuaidufu/libaibuaidufu.github.io
 * branch            HEAD       -> FETCH_HEAD
/usr/bin/git worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/master
Preparing worktree (detached HEAD cef818f)
HEAD is now at cef818f Site updated: 2020-08-05 17:47:31
/usr/bin/rsync -q -av --checksum --progress public/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
/usr/bin/git status --porcelain
....
?? 2020/08/06/
/usr/bin/git add --all .
error: insufficient permission for adding an object to repository database /home/runner/work/private-blog-deploy-actions/private-blog-deploy-actions/.git/objects
error: 2020/08/04/hello-world/index.html: failed to insert into database
error: unable to index file '2020/08/04/hello-world/index.html'
fatal: updating files failed
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

**Comment by libaibuaidufu** [comment]
finnally,  i build in local or use other action 
```
name: buildAndDeploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: libaibuaidufu/libaibuaidufu.github.io
        BRANCH: master 
        BASE_BRANCH: master 
        FOLDER: public 
```
