### ISSUE TITLE
Nothing is being deployed, even though there are files in the directory.

### ISSUE THREAD

**Issue by MidasLamb** [JamesIves/github-pages-deploy-action#397]
**Describe the bug**
Nothing is being deployed, even though there are files in the deployment directory.

**Reproduce**
Build the project and have it output something in the directory. Run the github action:
```
name: Build and deploy

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false # Required for Deploy to work.
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Make directory structure
      run: mkdir static/style
    - name: Build WASM
      run: wasm-pack build --target web --out-name wasm --out-dir "static"
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.6
      with:
        source: scss/main.scss
        destination: static/style/main.css
    - name: ls
      run: ls static && ls static/style
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: static # The folder the action should deploy.
```

**Logs**
![image](https://user-images.githubusercontent.com/14802865/90666782-2e47b800-e24e-11ea-9473-4b7c5b9269d8.png)

**Additional Comments**
If you want the raw logs I can provide those, but in the screenshot you can clearly see there is something in the folder I want to deploy (the step with `ls`)

Also, doing the worktree and rsync command locally does fill the temp directory with the correct items, and running `git status --porcelain` results in the following:
```
$ git status --porcelain 
?? github-pages-deploy-action-temp-deployment-folder/
``` 
Which I think is the expected behaviour?

But then checking the branch in github, it's empty:
![image](https://user-images.githubusercontent.com/14802865/90667315-e83f2400-e24e-11ea-8341-d2d97fc2745e.png)
