### ISSUE TITLE
Update README to include CLEAN option or make it default in version 4

### ISSUE THREAD

**Issue by zfletch** [JamesIves/github-pages-deploy-action#405]
The fact that this action does not remove files without the `CLEAN` option is not intuitive (at least to me) and it looks like it's a constant source of issues (https://github.com/JamesIves/github-pages-deploy-action/issues/398, https://github.com/JamesIves/github-pages-deploy-action/issues/300, https://github.com/JamesIves/github-pages-deploy-action/issues/277, https://github.com/JamesIves/github-pages-deploy-action/issues/146, https://github.com/JamesIves/github-pages-deploy-action/issues/75).

I think that the `CLEAN` option should either default to `true` in versions 4+ or, if that is too much of a disruption, it should be mentioned in the first example shown on the `README.md` file, e.g.:

```yaml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
```

or even

```yaml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          # CLEAN: true # Automatically remove deleted files from the deploy branch
```

This would probably save you the pain of having to deal with new issues about the same thing every few weeks. Ideally everyone would read the documentation before using the action, but that's often not the case, and people only look at the example.

Whether or not you decide to make any changes based on this issue, thank you for all your work on the action.
