### ISSUE TITLE
pipeline completed successful but no change are visible

### ISSUE THREAD

**Issue by daniele-zurico** [JamesIves/github-pages-deploy-action#42]
**Describe the bug**
Hi there,
I'm experiencing a weird behaviour with gatsby blog, gh-pages and github actions. Pretty much despite it deploy I'm not able to see the changes.

These are the steps I performed:
- I created my workflow/main.yml file as described on the doc:
```
name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: develop
          BRANCH: master
          FOLDER: public
          BUILD_SCRIPT: npm install && npm run-script build

```
- I created my personal access token: `https://github.com/settings/tokens`
- I put the personal access token in the `settings/secret` and I named it: `ACCESS_TOKEN`
- When I push a new change the pipeline start and complete successful to master: https://github.com/daniele-zurico/daniele-zurico.github.com/commit/571c67c6247ef5bbba0f707daeafdefc9019ee81/checks?check_suite_id=289705357
- the master branch contain the changes: `https://github.com/daniele-zurico/daniele-zurico.github.com/blob/master/page-2/index.html` : ` <h1>Hi from the second page</h1>`
- but going to my blog: https://daniele-zurico.github.io/page-2/ it doesn't reflect the changes.

If instead, I run from my machine: `npm run deploy`: https://github.com/daniele-zurico/daniele-zurico.github.com/blob/develop/package.json
Everything works as expected.

Can someone tell me what I'm doing wrong, please?
