### ISSUE TITLE
Add a dependabot.yml file

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#420]
GitHub now allows you to specify a `.github/dependabot.yml` file. You can find [documentation](https://dependabot.com/docs/config-file/) for this here, the base template looks like this:

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

```

It would be a good idea to add this configuration to future proof dependency updates. This would also be a great first issue for Hacktoberfest contributors.
