### ISSUE TITLE
Supposed this action can trigger 'page_build' or 'deployment'

### ISSUE THREAD

**Issue by Mister-Hope** [JamesIves/github-pages-deploy-action#421]
**My config:**

https://github.com/Hope-Studio/Hope-Studio.github.io/blob/master/.github/workflows/deploy-server.yml

```yml
name: Deploy blog to server

on:
  - deployment
  - page_build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mrhope.site >> ~/.ssh/known_hosts
          git config --global user.name 'Mr.Hope'
          git config --global user.email 'zhangbowang1998@gmail.com'
      - name: Deploy
        run: |
          git push -f git@mrhope.site:/www/wwwroot/hope gh-pages
          ssh git@mrhope.site "cd /www/wwwroot/hope && git reset --hard HEAD"
```

I am hoping the workflow above being triggered after github pages is deployed by the workflow below

https://github.com/Hope-Studio/Hope-Studio.github.io/blob/master/.github/workflows/deploy-github.yml

```yml
name: Deploy blog to github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0

      - uses: actions/cache@v2
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build Blog
        run: yarn run super:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: dist
```

**Action list**

https://github.com/Hope-Studio/Hope-Studio.github.io/actions

**Addtional info**

When I am using acecess token, `page_build` can be triggered, but not with Github Token.
