### ISSUE TITLE
Tolerate error on "git remote rm origin"

### ISSUE THREAD

**Issue by doegox** [JamesIves/github-pages-deploy-action#429]
When deploying, the action is doing sth like this:
```
/usr/bin/git init
/usr/bin/git config user.name xxxx
/usr/bin/git config user.email xxxx
/usr/bin/git remote rm origin
/usr/bin/git remote add origin xxxx
/usr/bin/git fetch --no-recurse-submodules
```
But if the top dir is not a git repo (e.g. because the Checkout action was configured with a subdir path), the `git remote rm origin` step will fail. So I suggest to do sth like `git remote rm origin || true`.

Right now I'm doing as workaround during the run:
```
/usr/bin/git init
/usr/bin/git remote add origin foo
```

The issue can be reproduced with sth like
```
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          repository: some-other-repo
          persist-credentials: false
          path: build

      - name: Checkout albums 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          path: build/web/albums

      - name: Install and Build 🔧
        run: |
          do-stuff-to-add-content-to-existing-build/web
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
```
