### ISSUE TITLE
Deployment fails if BRANCH already exists on remote

### ISSUE THREAD

**Issue by sudkumar** [JamesIves/github-pages-deploy-action#43]
**Describe the bug**

> Please provide a clear and concise description of what the bug is.

I have developed a portfolio website of mine which I want to host on github pages at https://sudkumar.github.io/. My development branch is `src` and the `master` branch should contain the website code (build folder). I have integrated the actions and it worked for the first deployment and created a master branch from my build folder ([here](https://github.com/sudkumar/sudkumar.github.io/commit/f4e3337eafacd67a3c3de73e2ec5b74025c0f4d3/checks?check_suite_id=293471807#step:7:252)). But when deploying again (now the master branch already exists on remote), the deployment deletes the `master` branch without creating it again ([here](https://github.com/sudkumar/sudkumar.github.io/commit/a9202005212fb35ae5596d9b9a6a88a9b74d08cf/checks?check_suite_id=293485598#step:7:119)).  And this happens for all alternate deployments.

It throws this error.
```bash
Deploying to GitHub...
Error: Use --prefix instead of bare filenames.
To https://github.com/sudkumar/sudkumar.github.io.git
 - [deleted]         master
Deployment succesful!
```

**Reproduce**

> Steps to reproduce the behavior.

Please have a look at my [deployment actions](https://github.com/sudkumar/sudkumar.github.io/blob/src/.github/workflows/deploy.yml)

**Expected behavior**

> Please provide a clear and concise description of what you expected to happen.

I expect it to push the new deployment to the master branch with the new commit.

**Work Around**
I have created a step to delete the master branch before the deployment step.

https://github.com/sudkumar/sudkumar.github.io/blob/5e166f27170660561d48156fd45498b627ec40ae/.github/workflows/deploy.yml#L16-L23

Please let me know if you need more details or I can be of some help in resolving this issue.

**Comment by sudkumar** [comment]
I cloned your action locally to test the deployment and added some echo statements. I found out that `git subtree split --prefix $FOLDER $BASE_BRANCH` throws this error when deploying again.
```
Error: Use --prefix instead of bare filenames.
```

**Comment by sudkumar** [comment]
I tested `git subtree split --prefix $FOLDER $BASE_BRANCH` locally to get the hash and it works just fine. It may be an issue with git version but I am not sure.

I update this command with

```
git subtree split --prefix $FOLDER ${BASE_BRANCH}_build
```

and it working. I don't know what the issue is or is it the correct way of doing it.

**Comment by JacksonMaxfield** [comment]
My team also ran into this issue as well. We believed the issue was due to GitHub not liking that there was only ever a single commit in the `gh-pages` branch / whichever branch you deploy to. Something to do with their caching mechanism maybe? Regardless, we also wanted there to be a git history for the deploy branch so we made more extensive changes.

A bulk of the changes are in [this commit](https://github.com/JacksonMaxfield/github-pages-deploy-action-python/commit/bbf57418fe52f4e5961a6516e419aa9cd095782d) but the current `@master` version is [here](https://github.com/JacksonMaxfield/github-pages-deploy-action-python/blob/master/entrypoint.sh).

**Note:** My fork uses is ran in an ubuntu / python image so we can build docs and such.

On higher level, I would assume these issues are naturally resolved by version three and both @sudkumar and my fixes are temporary solutions until that is released.

**Comment by sudkumar** [comment]
@JacksonMaxfield Thanks. Yours is much better than mine as keeping the history is essential. My `gh-pages` stopped working (no idea why 😕 ) after the actions integration. I will give yous a try.

**Comment by JamesIves** [comment]
Just catching up on this now as I’ve been traveling. I’ll see what I can do about pushing up version 3 this weekend.

**Comment by sudkumar** [comment]
@JamesIves Thank you. Please let me know if any way I can help in the release.

**Comment by JamesIves** [comment]
https://github.com/JamesIves/github-pages-deploy-action/pull/44 PR is up for the release, still a few more things to finish up but it should be testable now.

**Comment by JamesIves** [comment]
Alright! I've finalized most of the details and I'm ready for some people to give this a try. I'd love to push this up before I fly to San Francisco for Chrome Dev Summit.

You can try the beta out using the following: `JamesIves/github-pages-deploy-action@releases/v3-beta`. Let me know if you spot any issues.

**Comment by sudkumar** [comment]
Hi @JamesIves  I tried the `v3-beta` but got the following error.

```sh
git ls-remote --heads https://***@github.com/sudkumar/sudkumar.github.io.git master | wc -l
068dab7e7778d41ef7391d733959ef0af48e2c6b	refs/heads/master
git checkout src
fatal: 'src' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
##[error]The process 'git' failed with exit code 128
Deployment Successful!
##[error]Node run failed with exit code 1
```

[Deployment](https://github.com/sudkumar/sudkumar.github.io/commit/216ae89a6fcba23e09f070ebebe29b3dbb10d3e8/checks?check_suite_id=303101400#step:7:16) 

<details open>
<summary>
Logs
</summary>

```sh
Run JamesIves/github-pages-deploy-action@releases/v3-beta
git init
Reinitialized existing Git repository in /home/runner/work/sudkumar.github.io/sudkumar.github.io/.git/
git config user.name sudkumar
git config user.email 6812992+sudkumar@users.noreply.github.com
git ls-remote --heads https://***@github.com/sudkumar/sudkumar.github.io.git master | wc -l
068dab7e7778d41ef7391d733959ef0af48e2c6b	refs/heads/master
git checkout src
fatal: 'src' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
##[error]The process 'git' failed with exit code 128
Deployment Successful!
##[error]Node run failed with exit code 1
```

</details>

<details open>
<summary>Workflow</summary>

```yml
name: Build and Deploy
on:
  push:
    branches:
      - src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install
        env:
          CI: true
        run: |
          npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000

      - name: Build
        env:
          CI: true
        run: |
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-beta
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: src # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          BUILD_SCRIPT: npm run-script build # The build script the action should run prior to deploying.
          COMMIT_NAME: Sudhir Mitharwal
```
