### ISSUE TITLE
fatal 'src' could be both a local file and a tracking branch.

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#45]
```sh
git ls-remote --heads https://***@github.com/sudkumar/sudkumar.github.io.git master | wc -l
068dab7e7778d41ef7391d733959ef0af48e2c6b	refs/heads/master
git checkout src
fatal: 'src' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
##[error]The process 'git' failed with exit code 128
Deployment Successful!
##[error]Node run failed with exit code 1
```

[Deployment](https://github.com/sudkumar/sudkumar.github.io/commit/216ae89a6fcba23e09f070ebebe29b3dbb10d3e8/checks?check_suite_id=303101400#step:7:16) 

<details open>
<summary>
Logs
</summary>

```sh
Run JamesIves/github-pages-deploy-action@releases/v3-beta
git init
Reinitialized existing Git repository in /home/runner/work/sudkumar.github.io/sudkumar.github.io/.git/
git config user.name sudkumar
git config user.email 6812992+sudkumar@users.noreply.github.com
git ls-remote --heads https://***@github.com/sudkumar/sudkumar.github.io.git master | wc -l
068dab7e7778d41ef7391d733959ef0af48e2c6b	refs/heads/master
git checkout src
fatal: 'src' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
##[error]The process 'git' failed with exit code 128
Deployment Successful!
##[error]Node run failed with exit code 1
```

</details>

<details open>
<summary>Workflow</summary>

```yml
name: Build and Deploy
on:
  push:
    branches:
      - src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install
        env:
          CI: true
        run: |
          npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000

      - name: Build
        env:
          CI: true
        run: |
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-beta
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: src # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          BUILD_SCRIPT: npm run-script build # The build script the action should run prior to deploying.
          COMMIT_NAME: Sudhir Mitharwal
```

_Originally posted by @sudkumar in https://github.com/JamesIves/github-pages-deploy-action/issues/43#issuecomment-552072364_
