### ISSUE TITLE
Build failed because of environmental variable

### ISSUE THREAD

**Issue by angelod1as** [JamesIves/github-pages-deploy-action#549]
**Describe the bug**
When running the action, instead of a successful build, it returns an error:

```
Error: Unable to process command '::set-env name=DEPLOYMENT_STATUS::skipped' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Reproduce**
Setup this simple action: 

```
name: Build and Deploy

on:
  push:
    branches:
      - master
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.

```

Run it and the errors will appear at the end.

**Logs**

This is the deploy log:

```
Run JamesIves/github-pages-deploy-action@3.5.9
  with:
    GITHUB_TOKEN: ***
    BRANCH: gh-pages
    FOLDER: build

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ FAQ/Wiki: https://github.com/JamesIves/github-pages-deploy-action/wiki
    🔧 Support: https://github.com/JamesIves/github-pages-deploy-action/issues
    ⭐ Contribute: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md

    📣 Maintained by James Ives (https://jamesiv.es)
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/linkbio/linkbio/.git/
/usr/bin/git config user.name angelod1as
/usr/bin/git config user.email oiangelodias@gmail.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/angelod1as/linkbio.git
/usr/bin/git fetch --no-recurse-submodules
From https://github.com/angelod1as/linkbio
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      master     -> origin/master
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/angelod1as/linkbio.git gh-pages | wc -l
f60246bca6efa4ff13b055f6bb8f1a2710705ebd	refs/heads/gh-pages
/usr/bin/git checkout --progress --force a98f65ae1be707dc1cfcc45ec4a4d0b6b6847450
Note: switching to 'a98f65ae1be707dc1cfcc45ec4a4d0b6b6847450'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a98f65a Merge pull request #6 from angelod1as/dependabot/npm_and_yarn/ini-1.3.8
/usr/bin/git fetch ***github.com/angelod1as/linkbio.git
From https://github.com/angelod1as/linkbio
 * branch            HEAD       -> FETCH_HEAD
/usr/bin/git worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/gh-pages
Preparing worktree (detached HEAD f60246b)
HEAD is now at f60246b Deploying to gh-pages from  @ a98f65ae1be707dc1cfcc45ec4a4d0b6b6847450 🚀
/usr/bin/rsync -q -av --checksum --progress build/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
/usr/bin/git status --porcelain
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
Error: Unable to process command '::set-env name=DEPLOYMENT_STATUS::skipped' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Additional Comments**
I don't know exactly what other information I should offer. Below is the repo url. I'll help with anything I can.

https://github.com/angelod1as/linkbio
