### ISSUE TITLE
Error: Input required and not supplied: FOLDER

### ISSUE THREAD

**Issue by njzjz** [JamesIves/github-pages-deploy-action#56]
**Describe the bug**

```
Run JamesIves/github-pages-deploy-action@releases/v3
/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v3/node_modules/@actions/core/lib/core.js:69
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: FOLDER
    at Object.getInput (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v3/node_modules/@actions/core/lib/core.js:69:15)
    at Object.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v3/lib/constants.js:14:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v3/lib/git.js:22:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
##[error]Node run failed with exit code 1
```
https://github.com/njzjz/njzjz.github.io/runs/310999897#step:9:11

**Reproduce**

```
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.ref == 'refs/heads/hexo'
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: hexo
        BRANCH: master
        FOLDER: public
```

**Expected behavior**

run successfully

**Screenshots**

**Additional Comments**
