### ISSUE TITLE
Unable to deploy using Access Token

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#579]
**Describe the bug**

Using `releases/v4` I was unable to deploy using an access token if `persist-credentials: false` is set within the checkout step. 

**Reproduce**

* Setup a workflow using the following configuration. the `token` should be a GitHub PAT with a wide scope range that has adequate permissions.
* Run the following workflow. Ensure that `persist-credentials` is set to `false` on the checkout step, handing full control over to the deployment step for credentials. 
* You will receive the error: `fatal: could not read Username for 'https://github.com': No such device or address`

```yml
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run-script build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with: 
          branch: gh-pages
          folder: 'build'
          token: ${{ secrets.PUSH_TOKEN }}
```

**Logs**

https://github.com/JamesIves/reddit-viewer/runs/1811925681?check_suite_focus=true

**Additional Comments**

This is likely caused [here](https://github.com/JamesIves/github-pages-deploy-action/blob/dev-v4/src/util.ts#L22). [In v3 the username is setup slightly differently](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/util.ts#L28-L30) as the access token and github token did not share the same field.
