### ISSUE TITLE
Unable to deploy using default token field

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#580]
**Describe the bug**

I am unable to deploy using the default set `github.token` field in the  [action.yml file](https://github.com/JamesIves/github-pages-deploy-action/blob/dev-v4/action.yml#L32) if `persist-credentials` is set to `false` in the checkout step.

**Reproduce**

* Setup a workflow using the following configuration, the `token` should be _unset_, and rely on the provided one set by the `action.yml` file.
* Run the following workflow. Ensure that `persist-credentials` is set to `false` on the checkout step, handing full control to the deployment step for credentials.
* You will receive the error: `fatal: could not read Username for 'https://github.com': No such device or address`

```yml
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run-script build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with: 
          branch: gh-pages
          folder: 'build'
```

**Logs**

https://github.com/JamesIves/reddit-viewer/runs/1811925681?check_suite_focus=true

**Additional Comments**

This is very likely related #579
