### ISSUE TITLE
Running single-commit results in unusual logging

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#581]
**Describe the bug**

Using the `single-commit` input results in a large and unusual logfile. It seems to be printing the contents of every file it reads on the branch.

**Reproduce**

* Use the following workflow.
* Run `single-commit: true` to squash commits on the branch.
* Observe the logs it outputs.

```yml
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run-script build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with: 
          branch: gh-pages
          folder: 'build'
          single-commit: true

```

**Logs**

https://github.com/JamesIves/reddit-viewer/runs/1812014985?check_suite_focus=true

**Additional Comments**

The actual operation completes the branch commits do get squashed, only the logs are weird.
