### ISSUE TITLE
Build error: spawn rsync ENOENT

### ISSUE THREAD

**Issue by LeMorrow** [JamesIves/github-pages-deploy-action#65]
**Describe the bug**
I am trying to generate static html and then deploy it to the `gh-pages` branch. I am getting the following error:
```
There was an error when attempting to execute the process 'rsync'. This may indicate the process failed to start. Error: spawn rsync ENOENT
```

**Reproduce**
The error occurs when I open a pull request from `master` into `release` with the following build script:
```yml
name: .NET Core

on: 
  push:
    branches: 
      - "release"
  pull_request:
    branches: 
      - "release"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Install DocFX
      run: choco install docfx

    - name: Generate static documentation with DocFX
      run: docfx build docs/docfx.json
      
    - name: Deploy documentation to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: release
        BRANCH: gh-pages
        FOLDER: docs/_site
```

**Expected behavior**
No errors, successful deployment.

**Screenshots**
[![image](https://user-images.githubusercontent.com/35617441/69501342-5b0bb080-0f04-11ea-9713-d9294825bde9.png)](https://github.com/LeMorrow/APOD.Net/pull/31/checks?check_run_id=318371187#step:6:24)

**Additional Comments**
Link to this run and the error: [https://github.com/LeMorrow/APOD.Net/pull/31/checks?check_run_id=318371187#step:6:24](https://github.com/LeMorrow/APOD.Net/pull/31/checks?check_run_id=318371187#step:6:24)

Note that I am using Windows, which I have to do in order to install DocFX.

**Comment by JamesIves** [comment]
> Note that I am using Windows, which I have to do in order to install DocFX.

I'm pretty sure this is the reason for the failure as `rsync` isn't native on Windows. I tested this in my own repository by changing a working config from `ubuntu-latest` to `windows-latest` and got the same result.

This action is pretty dependent on `rsync` but I think there's probably three options we can explore:

1. Create a job that installs `cwRsync` [(link)](https://www.itefix.net/cwrsync) and adds `rsync` to the path. There's a StackOverflow post on this [here](https://stackoverflow.com/a/30997961/4933483), I'm not sure if it's possible or not in an action though.
2. Update your workflow config to create a second job that uses ubuntu, and pass the build files [back and forth using artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow).
3. Replace `rsync` that is cross operating system compatible.

**Comment by LeMorrow** [comment]
Thanks for the fast reply! I will try some things in the upcoming days and keep you updated on this. In the meantime, it might be good to add to the README that this action does not work for windows runners (does it work for mac runners?).

**Comment by JamesIves** [comment]
I've added  a section about support to the README. 

I think the failure in that action run is due to the use of Docker containers. I'm not sure if there's a equivalent way to force the action to fail based on operating system when it runs using Node.

**Comment by LeMorrow** [comment]
I tried passing the files back and forth using artifacts which worked really well! Thank you for the suggestion. Doing something similar to this will work as a workaround for anyone in the same position:
```yml
name: Deploy

on: 
  push:
    branches: 
      - "release"
  pull_request:
    branches: 
      - "release"

jobs:
  generate_docs:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Install DocFX
      run: choco install docfx
    
    - name: Generate site
      run: |
       docfx build docs/docfx.json
       dir docs/_site
      
    - name: Upload site artifact
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: docs/_site
  
  # Two different jobs because JamesIves/github-pages-deploy-action does not run on windows
  # and DocFX cannot easily be installed on ubuntu. 
  
  deploy:
    needs: generate_docs
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1
    
    - name: Download site artifact
      uses: actions/download-artifact@v1
      with:
        name: site
    
    - name: Do some debug logging
      run: |
       dir site
       echo --------------
       dir
    
    - name: Deploy site to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: release
        BRANCH: gh-pages
        FOLDER: site
```
