### ISSUE TITLE
`master` branch changed to `main`

### ISSUE THREAD

**Issue by LambertSchulze** [JamesIves/github-pages-deploy-action#675]
## Describe the bug

GitHub changed the naming of the master branch to `main`. The README still has the old naming convention:
```
on:
  push:
    branches:
      - master
```
change to
```
on:
  push:
    branches:
      - main
```
