### ISSUE TITLE
Subsequent back-to-back deployments result in a failure 

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JamesIves/github-pages-deploy-action#679]
I am publishing docs to multiple folders.

- Latest snapshot version to `snapshots`
- Specific versions to `versions/some-version`, e.g. `versions/0.1.0-alpha.14`

For some reason, snapshot version is working perfectly, but the specific version no.

The same setup, even the reports are the same.

As you can see, created folders are correct too:

```
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/gradle-plugins/gradle-plugins/build/dokka/. github-pages-deploy-action-temp-deployment-folder/snapshot --exclude .ssh --exclude .git --exclude .github
```

```
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/gradle-plugins/gradle-plugins/build/dokka/. github-pages-deploy-action-temp-deployment-folder/versions/0.1.0-alpha.15 --exclude .ssh --exclude .git --exclude .github
```

Workflows:
- [Snapshots](https://github.com/JavierSegoviaCordoba/gradle-plugins/actions/runs/775248082/workflow)
```
      - name: Deploy snapshot docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          target-folder: 'snapshot'
          branch: 'gh-pages'
          folder: 'build/dokka'
          clean: false
          single-commit: true
```
- [Specific version](https://github.com/JavierSegoviaCordoba/gradle-plugins/actions/runs/775265361/workflow)
```
      - name: Deploy release docs to Github Pages inside specific version folder
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          target-folder: 'versions/${{ steps.tags.outputs.version }}'
          branch: 'gh-pages'
          folder: 'build/dokka'
          clean: false
          single-commit: true
```

What is happening? I think it is impossible `build/dokka` is empty.

Maybe single-commit?
