### ISSUE TITLE
After deployment, the github pages file is 0 Bytes

### ISSUE THREAD

**Issue by bitbw** [JamesIves/github-pages-deploy-action#685]
## Describe the bug
After deploying github pages, HTML and other files are empty

## Reproduction Steps
![image](https://user-images.githubusercontent.com/55389796/116087889-e7ab3700-a6d3-11eb-9f5a-6e562d7fb2e5.png)
Files are emptied after deployment
![image](https://user-images.githubusercontent.com/55389796/116088323-58eaea00-a6d4-11eb-888c-9418f2074bc4.png)

### Actions
https://github.com/zhangbowen-github/my-blog/actions/runs/785638177

### logs
```
Run JamesIves/github-pages-deploy-action@4.1.1
  with:
    branch: gh-pages
    folder: public
    token: ***
    clean: true

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name zhangbowen-github
/usr/bin/git config user.email 55389796+zhangbowen-github@users.noreply.github.com
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/zhangbowen-github/my-blog.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/zhangbowen-github/my-blog.git gh-pages
6b5312978a1f6d5df4e1dd44b784fa87a20e063c	refs/heads/gh-pages
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
From https://github.com/zhangbowen-github/my-blog
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD a3ec583)
/usr/bin/git checkout -B gh-pages origin/gh-pages
Previous HEAD position was a3ec583 Update main.yml
Switched to a new branch 'gh-pages'
Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/my-blog/my-blog/public/. github-pages-deploy-action-temp-deployment-folder --delete --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
```

### workflow file
```yaml
name: Build and Deploy
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 
      - name: Install and Build 🔧 
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
```

## Additional Comments

Only @4.1.1 has this problem @releases/v2 does not have this problem

v2 workflow file
```yaml
name: GitHub Actions Build and Deploy Demo 
on:
  push:
    branches: 
      - master 
jobs: 
 build-and-deploy:
   runs-on: ubuntu-latest
   steps: 
   - name: Checkout 
     uses: actions/checkout@master
      
   - name: Build and Deploy 
     uses: JamesIves/github-pages-deploy-action@releases/v2
     env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      BASE_BRANCH: master
      BRANCH: gh-pages 
      FOLDER: public 
      BUILD_SCRIPT:  npm install && npm run build

```
