### ISSUE TITLE
defaults.run.working-directory is not respected

### ISSUE THREAD

**Issue by esemeniuc** [JamesIves/github-pages-deploy-action#699]
## Describe the bug
When I set `defaults.run.working-directory`, I would believe that the working directory would apply to the deployment. But it looks like `folder` still works from `/home/runner/MY_REPO/MY_REPO`

## Reproduction Steps
Add to top of workflow:
```yaml
defaults:
  run:
    working-directory: client
```
Use a deployment stage like this:
```yaml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: out # source folder path
          repository-name: gh-pages-frontend # target repo name
          branch: master # target branch name
          target-folder: docs
          clean: true # cleans the target repo destination
```

## Logs
```

Run JamesIves/github-pages-deploy-action@4.1.1

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Error: The directory you're trying to deploy named /home/runner/work/monorepo/monorepo/out doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
Deployment failed! ❌
```
## Additional Comments
I would expect the directory to be `/home/runner/work/monorepo/monorepo/client/out`

**Comment by JamesIves** [comment]
Can you show me the rest of your workflow? I'm mostly curious about your checkout/build step so I can reproduce this.

**Comment by esemeniuc** [comment]
This is the whole workflow: 

```yaml
name: Build and Deploy Client
on: [ push ]

defaults:
  run:
    working-directory: client

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Sanity Check + Yarn 2 ✅
        run: |
          echo "  - Node version: $(node -v)"
          echo "  - NPM version: $(npm -v)"
          yarn set version berry
          echo "  - Yarn version: $(yarn -v)"
          echo "  - Working in directory: $(pwd)"

      - name: Get yarn cache directory path ⚙️
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache check (and restore if cache-hit) ⚡
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps 🔧
        run: yarn install --immutable #reinstall because cache doesn't capture the entire install state

      - name: Build FE 🏗️
        run: yarn ghpublish

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: client/out # source folder path
          repository-name: gh-pages-frontend # target repo name
          branch: master # target branch name
          target-folder: docs
          clean: true # cleans the target repo destination
```

**Comment by JamesIves** [comment]
Thanks, I'll update you once this is ready.

**Comment by esemeniuc** [comment]
Awesome, thanks :)

**Comment by JamesIves** [comment]
I did some research on the `working-directory` option today and I believe there's an error in your workflow based on what I've researched. As you've set the base working directory to `client` there's no need to include it in the directory path. The following should work for you:

```yml
defaults:
  run:
    working-directory: client
```

```yml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: out
          repository-name: gh-pages-frontend
          branch: master
          target-folder: docs
          clean: true
```

The only variable that is available to action creators for this purpose is `process.env.GITHUB_WORKSPACE` [which should automatically context switch](https://docs.github.com/en/actions/reference/environment-variables) when a working-directory value is provided. I was able to use this pattern in my own workflow and it worked without issue. 

Lemme know if this is helpful and if it works for you.

**Comment by JamesIves** [comment]
Checking in to see if this worked for you or not? If so I'm going to close this issue.

**Comment by kebshell** [comment]
@JamesIves Thanks for putting time into creating this action (and others)! These provide such a time savings over manually figuring out the behavior and many rounds of testing to handle weird behaviors.

My goal is to publish our storybook files to GitHub Pages. For caching reasons, we checkout the repo into a different path under the workspace root.

I ran into your comment above while hunting for ways to adjust the `working-directory` for this action. Unfortunately you had no response from OP on the success/failure of that solution.

<details>

<summary>Workflow file</summary>

```yaml
name: Publish Pages
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

defaults:
  run:
    working-directory: repo

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        uses: actions/checkout@v4
        with:
          path: "repo"
      -
        name: Yarn Install
        uses: ./repo/.github/actions/yarn-install
        with:
          working-directory: "repo"
      -
        name: Build Frontend
        env:
          NODE_ENV: "production"
        run: yarn workspace web run buildPages
      -
        name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: "repo/public/pages"
          branch: "gh-pages"
          target-folder: "pr-preview/pr-${{ github.event.pull_request.number }}"
          commit-message: "Deploy Pages for ${{ github.ref_name }} #${{ github.event.pull_request.number }}"
          clean: true
          force: false
```

</details>

With that workflow above, I am getting this output for `github-pages-deploy-action` step
```
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/repo/repo
/usr/bin/git config user.name kebshell
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

If I use `folder: "public/pages"`, the output for `github-pages-deploy-action` shows
```
Checking configuration and starting deployment… 🚦
Error: The directory you're trying to deploy named /home/runner/work/repo/repo/public/pages doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
Notice: Deployment failed! ❌
```

Curious if you have any suggestions to get this working.
