### ISSUE TITLE
How to push particular changes to a branch without affecting other files in it?

### ISSUE THREAD

**Issue by Anirban166** [JamesIves/github-pages-deploy-action#717]
Hi James, I wanted to use your GitHub Action to create a workflow that pushes particular changes in a commit (i.e. within a specific directory) to another branch. For e.g., I have a project with some R files (`.R` extension) in a repository within a folder named "R". Now if I commit a change to an R file there (say `R/xyz.R`, with a path filter for `R/**.R`) along with some other changes (say I update the readme too), I would like my workflow to push only the changes within the R/ directory to my gh-pages branch, and leave the rest of the files/folders in the gh-pages directory to be kept intact as it is. (The workflow is run on pushes to main, and I need to carry over just the changes in `R/*.R` to gh-pages) 

Here is an example of what I'm trying to convey: https://github.com/Anirban166/test-workflow/tree/main
And here is the workflow I'm using:
```yml
name: Commit changes to gh-pages
on:
  push:
    branches:
      - main
    paths:
      - R/**.R
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages 
          folder: R
```
Thing is, it removes everything else in my gh-pages branch and it just commits the changed `/**.R` files to it. How can I configure my workflow such that the rest of the files are left unaffected?

**Comment by JamesIves** [comment]
Have you tried adding `clean: false` with a combination of `target-folder` to your workflow inputs? From what you describe that _should_ do what you need. 

```yml
- name: Deploy 
  uses: JamesIves/github-pages-deploy-action@4.1.0
  with:
      branch: gh-pages 
      folder: R
      clean: false
      target-folder: '...'
```

Lemme know if that works for you. The project readme has explanations of each field.
