### ISSUE TITLE
Environment variables in target-folder

### ISSUE THREAD

**Issue by jacobwilliams** [JamesIves/github-pages-deploy-action#751]
## Describe the bug

I may be doing something wrong, but is there anything preventing me from using an environment variable in the `target-folder`? See below:

## Reproduction Steps

Snippet from yml file:

```yml

    - name: Set vars
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Deploy documentation for tagged release
      env:
        TAGNAME: ${{ steps.vars.outputs.tag }}
      if: matrix.gcc_v == 7 && startsWith(github.ref, 'refs/tags/')
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc  # The folder the action should deploy.
        target-folder: prev/${TAGNAME}  # deploy to a version-specific folder
```

## Logs

What is happening is that it's getting deployed to a folder called `prev/${TAGNAME}` (so not expanding the environment variable).
