### ISSUE TITLE
Fails to deploy if git is missing

### ISSUE THREAD

**Issue by gallais** [JamesIves/github-pages-deploy-action#767]
## Describe the bug

I am using a container that does not ship `git` to build my project's documentation.
The script seems to assume that `git` is present and fails hard when it cannot find it:

https://github.com/frex-project/idris-frex/runs/2837540306#step:7:23

## Reproduction Steps

Edit: forgot that the repo is private. So here's a copy of yaml file:

```yaml
name: Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:

      - name: Build HTML
        shell: bash
        run: |
          mkdir docs
          touch index.html

      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3

        with:
          branch: gh-pages
          folder: docs
```

## Logs

You can see the fail for said yaml file here:

```log
/usr/bin/docker exec  e4dde0b862d4da7043fe96bf010eeeab283e758b2bc8eec6da925e291a5c1d0f sh -c "cat /etc/*release | grep ^ID"

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: jamesiv.es
    💖 Support: github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
Error: There was an error initializing the repository: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable. ❌
Deployment failed! ❌
```
