### ISSUE TITLE
why exclude .github?

### ISSUE THREAD

**Issue by Neutree** [JamesIves/github-pages-deploy-action#850]
## why exclude .github folder?

https://github.com/JamesIves/github-pages-deploy-action/blob/3aa6c63566921358c27ff9fe948e9ddb49d8cdfc/src/git.ts#L137

exclude .git folder make sense, but .github can lead to some error, maybe it should be an option?

when I need to build my site on [main branch action](https://github.com/teedoc/teedoc.github.io/blob/main/.github/workflows/publish.yml) and publish to gh-pages branch, and execute action in gh-pages branch, it need to copy action yml files to gh-pages's .github folder, so I now have to commit manually to gh-pages

and I think manually change gh-pages is pretty bad operation.

and it's may not a bug, may a feature~ but it may cause some problem for newbies

## Reproduction Steps

e.g. my action [here](https://github.com/teedoc/teedoc.github.io/tree/gh-pages/.github/workflows)

publish.yml to deploy pages to gh-pages branch, and trigger gh-pages's sync_pages_to_gitee.yml action, I can only have to change sync_pages_to_gitee.yml manually in gh-pages branch, when I change actions in main branch, gh-page's yml file changes nothing

**Comment by JamesIves** [comment]
The reason `.github` is excluded is for this very reason, to prevent jobs from incorrectly running on a branch it's not intended for. However because most actions are properly scoped to a specific branch I think that change might be appropriate.

In the meantime is the issue that when you push to `main` the `sync_pages_to_gitee.yml` workflow is not running after it deploys to the `gh-pages` branch? As you're using a workflow_dispatch are you able to manually trigger the workflow through the `Actions` tab? 

<img width="462" alt="Screen Shot 2021-08-28 at 12 01 49 PM" src="https://user-images.githubusercontent.com/10888441/131223776-de097a23-bf16-4343-9f7b-ba336fe6d31b.png">

The other option is to manually commit a `.github` directory to your `gh-pages` branch, and then add `.github` to your `clean-exclude` list to prevent it from being wiped out on subsequent commits. This is very similar to how the `CNAME` file works.

```yml
      - name: Deploy 🚀 to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with: # more usage visit https://github.com/JamesIves/github-pages-deploy-action
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ steps.build_doc.outputs.out_dir }} # The folder the action should deploy.
          single-commit: true
          clean: true
          clean-exclude: |
             - .github
```
