### ISSUE TITLE
clean-exclude file getting deleted

### ISSUE THREAD

**Issue by tommypepsi** [JamesIves/github-pages-deploy-action#917]
## Describe the bug

I'd like to use this action to sync 2 repos with the exception of some setting files but for some reason the `clean-exclude` option doesn't seem to work.

## Reproduction Steps
So in my action I start by deleting the setting files and then use this action with the `clean-exclude` option in the hope that the setting files don't get deleted but they still get deleted. 

```yml
      - name: delete setting files
        run: |
          find ./src -type f -regextype "posix-egrep" -iregex './src/templates/.+?\.json' -delete
          find ./src -type f -regextype "posix-egrep" -iregex './src/config/settings_data\.json' -delete

      - name: Send changes to secondary repo
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: Development
          repository-name: something/repo-name
          folder: src # The folder the action should deploy.
          target-folder: src
          commit-message: Update from Primary repo
          token: ${{ secrets.PAT }}
          clean-exclude: |
            src/templates/*.json
            src/config/settings_data.json
```

## Additional Comments
I also tried not deleting the files before but then the setting files just gets updated. I'd like these files to be completely ignored by the action.

Is there something wrong with my "clean-exclude" or am I misunderstanding something with this feature? (or is it a bug somehow)
