### ISSUE TITLE
Will cancel default GitHub build and deploy workflow, triggering email notification on each push

### ISSUE THREAD

**Issue by fladd** [JamesIves/github-pages-deploy-action#953]
## Describe the bug

This action seems to run in addition to the default "pages-build-deployment" GitHub action that gets automatically added when GitHub pages are activated, and that cannot be deleted or permanently disabled (it will enable itself again).

As can be seen in the following screenshots, after each push, the default action runs, but then gets interrupted "since a higher priority waiting request for 'master' exists":

<img width="972" alt="image" src="https://user-images.githubusercontent.com/2971539/146623205-660d8bd3-9132-416b-a090-3dc5f6151499.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/2971539/146623375-82fe837e-07e3-4fa3-b77a-5667376e3c6d.png">

This cancellation triggers an email notification that an action failed. Every time "github-pages-deploy-action" runs:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/2971539/146623700-863e518c-5e2a-47ac-a67b-6f9d02e867d6.png">

## Reproduction Steps

* Add a workflow as described in the "Getting started" section
* Two actions will start to run:
  1. "pages-build-deployment" (the default GitHub pages action)
  2. "github-pages-deploy-action"
* "pages-build-deployment" will be cancelled
* github-pages-deploy-action" will finish
* "pages-build-deployment" will run again and finish

## Logs

Tested with workflow:

```
name: Build and Deploy

on:
  push:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[build]')
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install setuptools wheel
    - name: Install StuffPages
      run: |
        python -m pip install StuffPages
    - name: Build
      run: |
        stuffpages build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: master # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
        target-folder: docs # The folder to deploy to.

```

**Comment by JamesIves** [comment]
This is likely occurring because you're not using Jekyll, which is fine, there's just another step you need to take. In your deployment branch/folder, in this case looks like `master/docs`, create an empty file with the name of `.nojekyll`. Much like the CNAME file [this is protected from cleanup jobs](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/git.ts#L136-L137) clobbering it on each deploy so you can commit it directly, or you can make it part of your build job. 

The reason this is necessary is because GitHub Pages has a built-in Jekyll compiler that is used to generate documentation websites. I can't imagine it's used all that much these days but it still exists. By adding that file it will tell GitHub Pages that it's not a Jekyll site, and it will cease attempting to compile with it, thus stopping the emails. 

Let me know if that works.

**Comment by fladd** [comment]
Thanks for the response @JamesIves. I actually do have a .nojekyll file (in both `master` and `master/docs`). So I don't think the issue is related to me not using Jekyll. Any other ideas how to disable this default GitHub pages workflow?

**Comment by JamesIves** [comment]
Interesting- I can't think of anything that could cause this in terms of how this is written. The only time I've seen this is a few months back when the integration tests for this project were firing off of one another, which was causing multiple deployments to occur in quick succession. Because of that I'd get multiple attempts at the github-pages build job and one of them would fail in the stack causing the email. 

Is this happening on _every_ push, and if so do you have something in your repo which is firing off these jobs all at once? If possible do you have a link to your repo so I can take a look?

**Comment by JamesIves** [comment]
For some additional context the reason the `github-pages` build job exists to begin with is because GitHub runs its own job once content has been pushed to the branch designated as the GitHub Pages branch. This job essentially "deploys" it onto their server from the repository (think FTP, but probably not FTP). It's sort of a two pronged thing where this action handles the initial paperwork, and once it makes it to the branch GitHub takes over and makes it go live. The job is _meant_ to be hidden and run behind the scenes so disabling it wouldn't really do much good. Without that job your page would never update.

What just occurred to me is that you're essentially creating a push on top of the same branch/folder. You're deploying the `master/docs` folder to the `master/docs` folder. You're essentially pushing the built source for your docs back onto your uncompiled docs, which is going to cause multiple deployments to fire on top of each other and create a deployment loop. You may instead want to push your compiled docs to a different branch, or host your uncompiled docs in a different folder within the master branch. The following example will work if you were to host your uncompiled docs in the `src/docs` folder. 

```yml
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: master
        folder: src/docs # Host your uncompiled doc source code here
        target-folder: docs # Push your compiled docs here
```

This should hopefully prevent GitHub Pages from stacking up these jobs and prevent the emails. Let me know if that works.

**Comment by fladd** [comment]
Thanks for the explanation. I changed the structure of the repository according to your suggestion. However, the situation remains the same. The GitHub default build and deploy action is interrupted and I get an email that it failed.

The repository in question is this one: https://github.com/fladd/floriankrause.org.

**Comment by JamesIves** [comment]
Aha, I see the issue here. I forked your project and kicked off some builds, prior to this I setup GitHub Pages so it runs on the `master` branch within the `docs` folder as I believe this is what you've got set too. The configuration can be found below:

<img width="811" alt="Screen Shot 2021-12-22 at 7 54 24 AM" src="https://user-images.githubusercontent.com/10888441/147095955-2d35921d-7b0a-4056-9b09-692f6784ac47.png">

---

This is an example of a commit to your README within `src` without `[build]` in the commit name. As expected the first build stopped due to the `if` statement in the workflow, but `pages-build-deployment` still ran for some reason even though the commit was made in `src` and not `docs`.

<img width="960" alt="Screen Shot 2021-12-22 at 7 50 14 AM" src="https://user-images.githubusercontent.com/10888441/147095820-c60e6f7f-b079-4739-ad7b-45f86fb2d8d5.png">

---

When you combine this with a commit with `[build]` in the name, the same thing happens as the first commit even though the commit didn't occur in the `docs` directory, but instead in `src`:

<img width="957" alt="Screen Shot 2021-12-22 at 7 51 34 AM" src="https://user-images.githubusercontent.com/10888441/147096144-eae4754c-648d-433c-a58e-e3240aff1e22.png">

---

Once the deployment job finishes from this action and makes the commit to `docs` for you it fires off the second `pages-build-deployment` job which is expected:

<img width="958" alt="Screen Shot 2021-12-22 at 7 52 25 AM" src="https://user-images.githubusercontent.com/10888441/147096092-e5af6a19-7ac5-4f7b-95a2-9ea2a1249db2.png">

---

Because of this the second job cancels the first, which results in the build failure and an email being sent:

<img width="708" alt="Screen Shot 2021-12-22 at 7 52 41 AM" src="https://user-images.githubusercontent.com/10888441/147098162-8fa96b66-4138-4fe4-8224-5e9fcfc5773f.png">

---

Ultimately I believe this is an issue you may need to email GitHub Support over as it seems to be a bug with the GitHub Pages builder. I'm not sure why the `pages-build-deployment` task is running when you make a commit that is not the source folder for GitHub Pages. I would expect any commits made outside of `{root}/docs` to not fire this job, and the doubling up of builds from this job is what is causing the environment failure.

Sadly I don't have any contacts at GitHub but please feel free to direct them to this issue if you write into support!

**Comment by JamesIves** [comment]
With that being said if you don't _need_ to have your current structure, and you wish to avoid this issue entirely, you can simply change your GitHub configuration within Settings to point GitHub Pages to the `gh-pages` branch and modify your workflow like so:

```

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install setuptools wheel
      - name: Install StuffPages
        run: |
          python -m pip install stuffpages
      - name: Build
        run: |
          stuffpages build src
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: src/docs
          target-folder: docs
```

If you change the workflow first the action will handle the branch creation for you, and then you go make the modifications here:

<img width="806" alt="Screen Shot 2021-12-22 at 8 23 50 AM" src="https://user-images.githubusercontent.com/10888441/147099513-23fc95cb-7761-47a3-b71b-6168752b3e23.png">

---

With this you would:

1. Make changes to your docs on the master branch.
2. The action will build the changes and commit them to the `gh-pages` branch.
3. The `pages-build-deployment` job won't double up as you're not making a commit to the same branch that you're deploying from. (Even if it's outside of the gh-pages source).
